### ISSUE TITLE
std_numeric_limits_test does not work with -O0

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#806] opened 2018-03-28 23:08 UTC
#### Summary:
Our tests normally are compiled with -O3, which optimizes a bunch of undefined symbols away. When compiled with -O0, just one of these tests fail, std_numeric_limits_test (both fwd and mix mode, granted we use neither of these modes).

#### Reproducible Steps:
```
cd math
echo O=0 >> make/local
./runTests.py test/unit/math/fwd/core/std_numeric_limits_test.cpp 
```

#### Current Output:
```
g++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/cvodes-3.1.0/include -isystem lib/idas-2.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O0 -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O0 -DNO_FPRINTF_OUTPUT -pipe  -c -o test/unit/math/fwd/core/std_numeric_limits_test.o test/unit/math/fwd/core/std_numeric_limits_test.cpp
g++ -Wall -I . -isystem lib/eigen_3.3.3 -isystem lib/boost_1.66.0 -isystem lib/cvodes-3.1.0/include -isystem lib/idas-2.1.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -Wno-unused-function -Wno-uninitialized -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_HAS_PTHREAD=0 -isystem lib/gtest_1.7.0/include -isystem lib/gtest_1.7.0 -O0 -DNO_FPRINTF_OUTPUT -pipe -lpthread  -o test/unit/math/fwd/core/std_numeric_limits_test test/unit/math/fwd/core/std_numeric_limits_test.o lib/gtest_1.7.0/src/gtest_main.cc lib/gtest_1.7.0/src/gtest-all.o
test/unit/math/fwd/core/std_numeric_limits_test.o: In function `AgradFwdNumericLimits_All_Fvar_Test::TestBody()':
std_numeric_limits_test.cpp:(.text+0x2e): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::is_specialized'
std_numeric_limits_test.cpp:(.text+0xfd): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::is_specialized'
std_numeric_limits_test.cpp:(.text+0x60c): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::is_signed'
std_numeric_limits_test.cpp:(.text+0x6db): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::is_signed'
std_numeric_limits_test.cpp:(.text+0x149e): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::has_infinity'
std_numeric_limits_test.cpp:(.text+0x156d): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::has_infinity'
std_numeric_limits_test.cpp:(.text+0x163c): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::has_quiet_NaN'
std_numeric_limits_test.cpp:(.text+0x170b): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::has_quiet_NaN'
std_numeric_limits_test.cpp:(.text+0x17da): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::has_signaling_NaN'
std_numeric_limits_test.cpp:(.text+0x18a9): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::has_signaling_NaN'
std_numeric_limits_test.cpp:(.text+0x1978): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::has_denorm'
std_numeric_limits_test.cpp:(.text+0x1a47): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::has_denorm'
std_numeric_limits_test.cpp:(.text+0x2034): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::is_iec559'
std_numeric_limits_test.cpp:(.text+0x2103): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::is_iec559'
std_numeric_limits_test.cpp:(.text+0x21d2): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::is_bounded'
std_numeric_limits_test.cpp:(.text+0x22a1): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::is_bounded'
std_numeric_limits_test.cpp:(.text+0x2862): undefined reference to `std::numeric_limits<stan::math::fvar<double> >::round_style'
std_numeric_limits_test.cpp:(.text+0x2931): undefined reference to `std::numeric_limits<stan::math::fvar<stan::math::fvar<double> > >::round_style'
collect2: error: ld returned 1 exit status
make/tests:16: recipe for target 'test/unit/math/fwd/core/std_numeric_limits_test' failed
make: *** [test/unit/math/fwd/core/std_numeric_limits_test] Error 1
make -j24 test/unit/math/fwd/core/std_numeric_limits_test failed
exit now (03/28/18 19:05:20 EDT)
```

#### Current Version:
v2.17.0

**Comment by danluu** [comment] 2018-03-31 18:46
Just so no one else wastes time with this, I believe I have the fix for this (I think I know why this is happening and I fixed one of N errors; the fix for the other N-1 errors should be basically identical), but I should probably do my taxes before spending more time on this. I'll probably submit a PR this weekend, and if not this weekend, early next week.

**Comment by bob-carpenter** [comment] 2018-04-01 16:55
@seantalts --- would you mind tagging and assigning issues when you create them?  It helps important bugs like this not get lost in the shuffle.

**Comment by seantalts** [comment] 2018-04-01 22:13
How should I tag and assign?

**Comment by danluu** [comment] 2018-04-02 15:01
I think the issue is that, the way the code is previously written, it defines these members but doesn't explicitly initialize them.

If you want to know where to dig in the C++ standard to find out precisely when this is ok, I believe this can be done by looking at 9.4.2 "Static Data Members", item 2, plus where "use" is defined, which I think will require looking in multiple places.

Anyway, one fix for this would be to return these values from `constexpr` functions, but since the standard defines that these sorts of constants must be compile-time evaluated, I don't think that makes a difference in practice. The fix in #810 just initializes each member, which seems like the smallest change that will fix this.

**Comment by bob-carpenter** [comment] 2018-04-02 19:50
Initializing every member is always a good practice.

**Comment by bob-carpenter** [comment] 2018-04-02 19:53
Putting everything in a function would also be OK.  That's the new standard C++11 style for singletons like this.

**Closed** 2018-04-02 19:54 UTC
Labels: bug
