### ISSUE TITLE
Sir model missing parameter that used to be there

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#972] opened 2018-08-08 19:52 UTC
The performance-tests-cmdstan [started failing about 4 days ago](http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/CmdStan%20Performance%20Tests/detail/master/214/pipeline) (with a not great error message that I just committed a fix for) that basically means that [this sir model](https://github.com/stan-dev/stat_comp_benchmarks/blob/master/benchmarks/sir/sir.stan) is missing (at least) parameter `y.19.3` as of [this commit](https://github.com/stan-dev/stan/compare/1ce1d9dac91db494fc256966f5b98231a95f3ede...50a3777fdfc5997577e394d38ebc1ad8ea9ad064#diff-2fec84f6c95c77e57f4fc634179bd9cd). Tagging people on that commit (oh how I wish this were automated): @syclik @bbbales2 @drezap

## Current Math Version
v2.18.0

**Comment by syclik** [comment] 2018-08-08 23:55
It doesn't look like any of those files should have affected the test. Any
idea what the difference in behavior is from? Do we have the pre-fail
output CSV to compare against?

**Comment by seantalts** [comment] 2018-08-09 06:43
No idea, but maybe there was more that changed over that day than just that one PR - It went from CmdStan commit d74ca73 (which was fine) to commit f414adc (which was not fine).

It's testing against golds in the performance-tests-cmdstan repo: https://github.com/stan-dev/performance-tests-cmdstan/tree/master/golds (The SIR one is in there and hasn't changed since I added these tests 4 months ago)

**Comment by seantalts** [comment] 2018-08-09 06:48
Ah, yeah, tuples step 1 were apparently merged... Let me move this issue to the Stan repo.

**Comment by bbbales2** [comment] 2018-08-09 06:51
Does this seem like it could be an output parsing issue? The output is coming from cmdstan, right? And then is being pulled in by some python? Maybe there is a bug there? Do we have the output file that is failing to parse?

It seems unlikely that parameter itself is missing. Maybe naming changed?

Good catch at tuples. Did tuples affect how variables are named on the output?

**Comment by seantalts** [comment] 2018-08-09 06:58
I think it's a bug in the new generated code. The tuples branch refactored 400 something files in the Stan compiler.

**Comment by seantalts** [comment] 2018-08-09 07:00
To answer your other questions - nothing is failing to parse, the Python and gold files haven't changed in months, the output csv is just missing some parameters entirely. I actually think I already saw this bug or one very similar to it on this branch before and pointed it out to Mitzi a couple of months ago but I guess it didn't get fixed before merging.

**Comment by bbbales2** [comment] 2018-08-09 07:04
Oh okay. And the way to reproduce this outside the CI would be:

1st getting the right cmdstan
```
git clone --recursive https://github.com/stan-dev/cmdstan.git
git checkout f414adc
make stan-update
```

Downloading the model files here: https://github.com/stan-dev/stat_comp_benchmarks/tree/master/benchmarks/sir

Building them with cmdstan, and then running them using the commands here: https://github.com/stan-dev/stat_comp_benchmarks/blob/master/benchmarks/sir/sir.info ?

**Comment by seantalts** [comment] 2018-08-09 07:08
That wouldn't produce the gold files, but I assume it would show that the parameter is missing. The gold files are produced by [performance-tests-cmdstan](https://github.com/stan-dev/performance-tests-cmdstan) - you can clone that repo and do it all at home, even comparing two specific cmdstan commit hashes.

**Comment by bbbales2** [comment] 2018-08-09 07:11
Oooh oooh, i see, yeah that makes sense.

**Comment by bob-carpenter** [comment] 2018-08-09 09:02
How should we record these observations on works-in-progress so they don't get lost?  If it was just the branch, there wouldn't have been a PR to which a blocking review could have been added.

What needs to happen is that this needs to get turned into a regression test that's in the stan-dev/stan repo.

**Comment by bbbales2** [comment] 2018-08-09 09:29
I was able to reproduce this using the repo @seantalts posted and it looks like the indices on the output labeling are swapped. Run cmd was:

```./runPerformanceTests.py stat_comp_benchmarks/benchmarks/sir```

The generated file shows:
```
y.2.9 56.4478348 578.832217013
y.3.20 275.321868 5311.58643456
xi 10.46603202 14.1680948916
y.2.10 11.79825193 33.6391177314
y.3.13 5403.73992 145098.773782
y.2.20 409.766018 10287.1694835
delta 0.357509191 0.0181285359232
y.3.17 14016.3903 9365789.5694
y.3.16 10315.20306 5688204.63999
...
```

The correct file (which corresponds to the indexing in the model) looks like:
```
y.19.3 5999.48329 173066.638306
y.19.2 7.8300849 14.9109551986
y.19.1 3992.6869 174601.205331
y.20.4 184.521659 2676.1303086
y.20.3 6008.476 173723.368674
y.20.2 5.24983551 7.14818504699
y.20.1 3986.27408 174757.133088
y.19.4 275.087749 5255.73689457
y.12.2 117.180857 2122.57061943
...
```

That's enough sleuthin' for ol' Ben. I'ma go eat a baguette.

**Comment by seantalts** [comment] 2018-08-09 11:45
> How should we record these observations on works-in-progress so they don't get lost?  If it was just the branch, there wouldn't have been a PR to which a blocking review could have been added.

I showed Mitzi I think 3 bugs that these tests popped up during the PR (by commenting on the PR for most of them) and eventually said she ran all of the performance-cmdstan-tests and verified that they worked. I didn't verify, and maybe the PR changed since then. I also asked that something like these tests be incorporated into the PR if I was to sign off on it.

In general I don't think this pattern pops up a lot because developers are managing their own testing.

**Comment by syclik** [comment] 2018-08-09 12:25
From a process perspective, on review did you mark it as approved, comment,
or changes required? We may need to change our merge permissions on GitHub
if you marked it as needing changes, but was overridden by a positive
review.

There's now a new checkbox for dismissing approvals if there's a commit
after it's been approved. Maybe we should enable that?

**Comment by mitzimorris** [comment] 2018-08-09 12:26
thanks @bbbales2 for tracking down the error.
@seantalts these benchmark tests are useful.  I made several changes to the code w/r/t in the past month.  I forgot about these benchmark tests.

**Comment by seantalts** [comment] 2018-08-09 15:59
>From a process perspective, on review did you mark it as approved, comment,
or changes required? We may need to change our merge permissions on GitHub
if you marked it as needing changes, but was overridden by a positive
review.

I didn't submit a review, I was just trying to help out with the validation side of things.

> There's now a new checkbox for dismissing approvals if there's a commit
after it's been approved. Maybe we should enable that?

Sounds like maybe a good idea in general though it wouldn't have prevented this particular situation.

> @seantalts these benchmark tests are useful. I made several changes to the code w/r/t in the past month. I forgot about these benchmark tests.

I don't know the correct name, but they also test that HMC is still recovering means [within 30% of the old estimate](https://github.com/stan-dev/performance-tests-cmdstan/blob/master/runPerformanceTests.py#L199). Similar to the [stat comp benchmarks](https://github.com/stan-dev/stat_comp_benchmarks#statistical-computation-benchmarks). They failed because the script I wrote to do that was expecting all of the parameter names in the golden version to be present in the new version (and I hadn't anticipated that failure, meaning the error message was shitty and the tests stopped).

**Comment by seantalts** [comment] 2018-08-16 15:46
Check out these comparatively beautiful test results that clearly highlight the parameter differences: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/CmdStan%20Performance%20Tests/detail/master/253/tests

**Comment by bbbales2** [comment] 2018-08-16 17:14
Very nice!

**Closed** 2018-08-18 07:43 UTC
Labels: bug
