### ISSUE TITLE
higher order finite diff tests

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#66] opened 2015-07-06 21:52 UTC
_From @rtrangucci on January 21, 2015 1:17_

Currently, we have no finite diff tests for second and third order derivatives, but we should have higher-order finite diff tests.

_Copied from original issue: stan-dev/stan#1225_

**Comment by bob-carpenter** [comment] 2016-08-18 10:57
Duplicate of #65

**Closed by bob-carpenter** 2016-08-18 10:57 UTC
