### ISSUE TITLE
8 tests fail when run under valgrind

### ISSUE THREAD

**Issue by danluu** [stan-dev/math#815] opened 2018-04-04 20:26 UTC
#### Summary:

Some tests fail when run with valgrind. When I say fail, I mean that the normal test checks fail, not that valgrind is reporting memory leaks or other errors.

#### Description:

Here are the tests that fail when run under valgrind:

~~~
190:test_unit_math_fwd_scal_fun_modified_bessel_first_kind_test
473:test_unit_math_mix_scal_fun_modified_bessel_first_kind_test
777:test_unit_math_prim_mat_prob_skew_normal_test
866:test_unit_math_prim_scal_fun_log_modified_bessel_first_kind_test
881:test_unit_math_prim_scal_fun_modified_bessel_first_kind_test
1000:test_unit_math_prim_scal_prob_neg_binomial_test
1121:test_unit_math_rev_mat_fun_cholesky_decompose_test
1315:test_unit_math_rev_scal_fun_modified_bessel_first_kind_test
~~~

It's possible that this is more than one bug. I haven't debugged this at all yet.

Here's the gtest result from one of the tests when run under valgrind:

~~~
[ RUN      ] AgradFwdModifiedBesselFirstKind.Fvar
test/unit/math/fwd/scal/fun/modified_bessel_first_kind_test.cpp:22: Failure
Value of: x.val_
  Actual: nan
Expected: -3.95337021740260939647
Which is: -3.9533703
test/unit/math/fwd/scal/fun/modified_bessel_first_kind_test.cpp:23: Failure
Value of: x.d_
  Actual: nan
Expected: 2.0 * 3.5630025133974876
Which is: 7.1260052
[  FAILED  ] AgradFwdModifiedBesselFirstKind.Fvar (76 ms)
[ RUN      ] AgradFwdModifiedBesselFirstKind.FvarFvarDouble
test/unit/math/fwd/scal/fun/modified_bessel_first_kind_test.cpp:43: Failure
Value of: a.d_.d_
  Actual: -nan
Expected: 0
test/unit/math/fwd/scal/fun/modified_bessel_first_kind_test.cpp:50: Failure
Value of: b.d_.d_
  Actual: -nan
Expected: 0
[  FAILED  ] AgradFwdModifiedBesselFirstKind.FvarFvarDouble (11 ms)
~~~

Although valgrind can produce false positives, I suspect that, other than timeouts, failures that are actual test failures and not valgrind errors are relatively likely to be real bugs.

#### Reproducible Steps:

An easy way to reproduce this is to check out the `cmake` branch, build, and then run `ctest -T memcheck`. It should also possible to reproduce this with the "normal" build (I spot checked one of these tests and used valigrind with the "normal" build and got the same failure).

#### Current Version:

v2.17.0

**Comment by mcol** [comment] 2019-12-22 22:00
I've tried the tests mentioned above:

- test/unit/math/fwd/scal/fun/modified_bessel_first_kind_test: removed
- test/unit/math/rev/mat/fun/modified_bessel_first_kind_test: removed
- test/unit/math/mix/scal/fun/modified_bessel_first_kind_test:
```
[ RUN      ] mathMixScalFun.modifiedBesselFirstKind
./test/unit/math/expect_near_rel.hpp:92: Failure
Value of: stan::math::is_nan(x1) && stan::math::is_nan(x2)
  Actual: false
Expected: true
expect_near_rel(8.1539076013560905, -nan)
expect_near_rel; require items x1(i) = x2(i): hessian() Hessian

./test/unit/math/expect_near_rel.hpp:92: Failure
Value of: stan::math::is_nan(x1) && stan::math::is_nan(x2)
  Actual: false
Expected: true
expect_near_rel(8.1539076013560905, -nan)
expect_near_rel; require items x1(i) = x2(i): hessian_fvar() Hessian
```

- test/unit/math/prim/scal/fun/modified_bessel_first_kind_test:
```
[ RUN      ] MathFunctions.modified_bessel_first_kind
test/unit/math/prim/scal/fun/modified_bessel_first_kind_test.cpp:14: Failure
Expected equality of these values:
  -3.953370217402609396478635740580581287584221595
    Which is: -3.9533703
  modified_bessel_first_kind(-1, -3.0)
    Which is: nan
```

- test/unit/math/prim/scal/fun/log_modified_bessel_first_kind_test: OK
- test/unit/math/prim/mat/prob/skew_normal_test: OK
- test/unit/math/prim/scal/prob/neg_binomial_test.cpp: OK
- test/unit/math/rev/mat/fun/cholesky_decompose_test: removed
- test/unit/math/mix/mat/fun/cholesky_decompose_test: OK

**Comment by mcol** [comment] 2019-12-22 23:03
The failures mentioned above are all caused by the call to `boost::math::cyl_bessel_i()` present in `stan/math/prim/scal/fun/modified_bessel_first_kind.hpp`.

The interaction between Valgrind and `boost::math::cyl_bessel_i()` were already discussed in 2009 (https://sourceforge.net/p/valgrind/mailman/message/23297714/) and they boil down to the boost policy of using long doubles (80 bit precision), which exceeds the amount of precision that Valgrind supports 64 bits. The Valgrind issue is logged at https://bugs.kde.org/show_bug.cgi?id=197915, and it seems unlikely to be fixed in the foreseable future.

I recompiled the test with the additional `-DBOOST_MATH_PROMOTE_DOUBLE_POLICY=false` as was mentioned at the end of the mailing list thread note before, and the test showed no errors when run under Valgrind.

I think those errors are innocuous and outside of our control, and therefore we should close this issue as it's not actionable.

**Comment by syclik** [comment] 2019-12-23 04:36
Thanks, @mcol. Closing the issue; that explanation and digging into details is definitely a strong argument for closing the issue as-is.

**Closed by syclik** 2019-12-23 04:36 UTC
