### ISSUE TITLE
Give matrix_cl matrix type attributes

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1198] opened 2019-04-04 19:45 UTC
## Description

On my to-do list. Right now we have code in the OpenCL stuff that looks like

```cpp
  matrix_cl L_21
      = opencl::multiply<TriangularViewCL::Entire, TriangularViewCL::Upper>(
          A_21, transpose(lower_triangular_inverse(L_11)));
```

This lets us do optimized multiplications for matrix_cl's with specific characteristics. But the above is kind of a weird API to me. I'd like to have something like

```cpp
matrix_cl L_21 = A_21 * transpose(lower_triangular_inverse(L_11));
```

Where the LHS and RHS of * are `matrix_cl`s with a `TriangularViewCL matrix_view` (name subject to change) attribute. In functions where we know they will return a lower or upper triangular the function can change this value. Similarly things like transpose can see they are transposing a lower triangular to upper and change the `matrix_view` appropriately.

With that we can have the multiply code look at the `matrix_view` for each matrix and dispatch to the appropriate optimized multiplication or other optimized function

Sean / Rok, any weird gotchas or things I should think about when prototyping this?

## Example

```cpp
matrix_cl A<TriangularViewCL::Upper>(size, size);
matrix_cl B<TriangularViewCL::Entire>(size, size);
// This will do the optimized triangular * rectangular multiply
matrix_cl C = A * B;
```

## Expected Output

Output should stay the same

#### Current Version:
v2.19.0

**Comment by rok-cesnovar** [comment] 2019-04-05 05:38
Love this! I was not happy with the API either but had no good ideas on how to simplify it. This will definitely find some additional optimizations that we havent found manually.

Transpose, lower traingular inverse, cholesky decomopose, zeros etc seem clear candidates for setting/modifying the view. For kernels like add/subtract we should keep the view if both inputs have the same view, otherwise set to entire. But I am probably just repeating what you already know.

**Comment by seantalts** [comment] 2019-04-05 12:44
Yeah, this seems really good at least prima facie! Does this also imply we need to change e.g. `transpose` et al to be methods?

**Comment by SteveBronder** [comment] 2019-04-05 15:31
> Does this also imply we need to change e.g. transpose et al to be methods?

idt so, should it be? I think if something takes in a matrix_cl it can change the matrix_view.

Rok I was going to take a crack at fixing up the cache stuff on top of the async this weekend. Do you have any time on your plate to work on this? I figure it would look something like

1. Add a template to matrix_cl constructor like
```cpp
<TriangularViewCL matrix_view = TriangularViewCL::Entire>
...
```

Then add to private
```cpp
TriangularViewCL matrix_view = matrix_view;
```

2. For the methods and functions look through to see which outputs should have certain matrix_view properties
3. change multiply and other methods that can do specializations to dispatch out to those based on the matrix_view

Also on a sidenote, I got the enqueueMapBuffer stuff working for copying, but actually saw a slowdown? Maybe I was doing it wrong. I think to make the host side pointer definitely page locked we would need to actually use `mlock`

**Comment by rok-cesnovar** [comment] 2019-04-05 16:09
@SteveBronder Sure, I can take a crack at this.

**Comment by rok-cesnovar** [comment] 2019-04-15 09:09
@t4c1 volunteered to do this one, so I am assigning him

**Comment by t4c1** [comment] 2019-04-15 10:50
Since we have some methods that modify matrix_cl in-place (for example transpose) this can not be done with templates. Instead I will make it like this: 

```
matrix_cl A(size, size, TriangularViewCL::Upper);
matrix_cl B(size, size, TriangularViewCL::Entire);
// This will do the optimized triangular * rectangular multiply
matrix_cl C = A * B;
```

**Comment by t4c1** [comment] 2019-04-15 11:04
I will have to change signiture of `matrix_cl.sub_block()`. The problem is it accepts `TriangularViewCL` as a template parameter. With making `TriangularViewCL` an attribute of `matrix_cl` it can not be set as template parameter when `matrix_cl.sub_block()` is called from `opencl::multiply()`.

**Comment by seantalts** [comment] 2019-04-15 13:01
is it sufficient for `sub_block` to use the triangular attribute of the matrix_cl it is being written into? I can't find where sub_block is currently being called by opencl::multiply() but here is what used to happen and I think a good illustration of the pattern:
```cpp
  matrix_cl Apad(Mpad, Kpad);
  opencl_kernels::zeros(cl::NDRange(Mpad, Kpad), Apad.buffer(), Mpad, Kpad,
                        TriangularViewCL::Entire);
  Apad.sub_block<triangular_view_A>(A, 0, 0, 0, 0, A.rows(), A.cols());
```
This could now become:
```cpp
  matrix_cl<triangular_view_A> Apad(Mpad, Kpad);
  Apad.zeros();
  Apad.sub_block(A, 0, 0, 0, 0, A.rows(), A.cols());
```
(You can store the template parameter to Apad with a typedef member inside matrix_cl)

But this only works for the cases where the matrix_cl destination dictates what to copy from the source. There are some obvious hypothetical scenarios where this doesn't work, like if you wanted to copy the lower left triangle of A and the upper right of B into Apad. So if we have any of those cases (@rok-cesnovar or @SteveBronder ?), I think your solution with a sub_block override with an extra parameter indicating the triangularity makes sense to me.

**Comment by rok-cesnovar** [comment] 2019-04-15 13:42
The use of `sub_block` in `multiply` was removed when we got rid of padding, so triangular sub_block is not being used anywhere at the moment.

Currently, the `triangular_view` template parameter actually represents the triangular view of the source matrix (A in the example above), so we should take that matrices attribute in order to replicate the current behavior.

We should also probably take the triangular attribute of the destination matrix into account. We have two options: 

1. invalidate the triangular attribute if the developer touches elements above the triangular if lower triangular and vice versa
2. do not set elements above the triangular if lower triangular and vice versa

I am more for 2. but could also be persuaded otherwise.

**Comment by t4c1** [comment] 2019-04-15 14:37
Nevermind, I had an old version of develop branch.

I have a slight preference for the first option - seems more general.

**Comment by SteveBronder** [comment] 2019-04-15 16:15
I'm indifferent though I think (1) would be easier to setup

**Comment by rok-cesnovar** [comment] 2019-04-15 16:34
Lets go with the first option then.

**Comment by SteveBronder** [comment] 2019-04-15 17:39
Yeah so I think for (1) we can have
1. Template on constructor
2. Assign, lower and upper depending on operations. e.g. if we do transpose a  `Lower` then switch it to `Upper`
3. For upper/lower in sub_block, check that the place we are putting values keeps the triangular property and if not then make the type `Entire`

**Comment by SteveBronder** [comment] 2019-04-16 05:37
I started working on this here if anyone hasn't taken a stab yet

https://github.com/bstatcomp/math/tree/feature/opencl-matrix-views

Got a bit late and still need to write my part of the paper. I did the layups of the transposes, lower_tri_inverse, and cholesky. Also added `view()` and `set_view()` methods for the `matrix_cl`. For sub_block we need to check both the triangular view of the matrix and whether the new matrix is going into the part of the view it should not, if so set it to entire.

**Comment by SteveBronder** [comment] 2019-04-16 05:40
Also, that branch is branch'd from the async branch. I want to move the pack and unpack operations as matrix_cl constructor so we can call

```cpp
matrix_cl A<TriangularViewCL::Upper>(vec, M); // Makes an MxM and unpacks to upper
```

**Comment by SteveBronder** [comment] 2019-04-16 17:54
Actually @rok-cesnovar can you think of a case where promoting to Entire for disagreeing types would be incorrect? Aka this logic table. If that makes sense then I think we can utilize the new `write_buffer` and `read_buffer` semantics to assign the output type (`write_buffer`) automajically. At least for `+`, `*`, and `-`.

| Input1 | Input2 | Output |
|--------|--------|--------|
| Lower  | Lower  | Lower  |
| Lower  | Upper  | Entire |
| Lower  | Entire | Entire |
| Upper  | Upper  | Upper  |
| Upper  | Lower  | Entire |
| Upper  | Entire | Entire |

For transpose and in-place ops. I think we could add a value to the write buffer that the kernel could read and then assign the appropriate view. Something like

```cpp
// We could make this an enum so it looks nicer
struct write_buffer {
    int flip = 0;
}
...
// The kernel will know that if the type is `Lower` make it `Upper`
const kernel_cl<write_buffer(1), int, int, TriangularMapCL> triangular_transpose(...)
```

@seantalts do you have any thoughts about this? Would be nice to not have a bunch of if statements in the code if we can get away with something like this

**Comment by seantalts** [comment] 2019-04-16 19:14
> so we should take that matrices attribute in order to replicate the current behavior.

Do we want to or need to replicate the current behavior if it's not used? Is it already clear we'll need it soon?

> https://github.com/bstatcomp/math/tree/feature/opencl-matrix-views

I wouldn't call these views... typically a view refers to something a bit different, e.g. http://www.modernescpp.com/index.php/c-17-avoid-copying-with-std-string-view

> @seantalts do you have any thoughts about this? Would be nice to not have a bunch of if statements in the code if we can get away with something like this

Hmm, I think 1) it will have to be more complicated than the example you posted and 2) I'm not sure you can reasonably always include triangularity flipping as an attribute on a write buffer. For example if you have two input matrices, which matrix's triangularity gets flipped? Would be worth working out in advance. 

Also I think @t4c1 volunteered to take a crack at this one already, he just didn't get assigned because I guess he's not in the stan-dev organization yet and github doesn't let you assign to collaborators or something.

**Comment by rok-cesnovar** [comment] 2019-04-16 20:20
> Also I think @t4c1 volunteered to take a crack at this one already, he just didn't get assigned because I guess he's not in the stan-dev organization yet and github doesn't let you assign to collaborators or something.

Yeah, I tried to clear me, you and Steve and assign Tadej, but then realized I cant, since its limited to stan-devs. Pretty embarrassing on my part :)

**Comment by rok-cesnovar** [comment] 2019-04-16 20:23
Also Tadej has started working on other minor tasks and preparing the GPU GLM branches for when caching is merged, so no worries there.

**Comment by SteveBronder** [comment] 2019-04-16 22:45
Aight I'll push off on this, weird and fun q I think on how to do this nicely though

> 1) it will have to be more complicated than the example you posted

Probably, but idt that much?

> 2) I'm not sure you can reasonably always include triangularity flipping as an attribute on a write buffer. For example if you have two input matrices, which matrix's triangularity gets flipped? Would be worth working out in advance.

I think we would take the 'promoted' output value of the table above. If the output from that is Lower and flip is true then we get Upper. It feels like that makes sense

When I started working through this I think we could end up with a lot of accidental gotchas if we try to do it by hand with a bunch of if statements

**Comment by seantalts** [comment] 2019-04-16 23:03
What about something like `lower triangular C = diag_mat_mul_tri_transpose(upper triangular A, square B)`? is that possible?

**Comment by seantalts** [comment] 2019-04-16 23:03
> When I started working through this I think we could end up with a lot of accidental gotchas if we try to do it by hand with a bunch of if statements

Definitely agree that `!=` is much easier to code up than a bunch of special cases, haha.

**Comment by SteveBronder** [comment] 2019-04-17 03:49
> What about something like `lower triangular C` = `diag_mat_mul_tri_transpose(upper triangular A, square B)`? is that possible?

Not sure if I'm following?

**Comment by seantalts** [comment] 2019-04-17 12:54
I'm trying to come up counterexamples for where the `!=` chart + a flip bit doesn't lead to the best answer before we start coding it. I don't think my example makes sense because multiplying a triangular and a full square matrix doesn't preserve triangularity, but if there was such an operation that would break the mold. Another thing to think about here is other matrix attributes and how they might interact. What does Eigen do here?

**Comment by SteveBronder** [comment] 2019-04-17 14:27
> What does Eigen do here?

That's the plan sam. I'm going to try to rubber duck their code this weekend to get a better idea of what happens under the hood

**Comment by t4c1** [comment] 2019-06-11 21:01
@SteveBronder are you working on this right now? Can I take over?

**Comment by SteveBronder** [comment] 2019-06-11 21:13
Totes feel free to takeover! idt we've decided a clear path for this so if you have any thoughts on how to do this feel free to share!

**Comment by t4c1** [comment] 2019-06-12 07:30
One option I see is following the way Eigen does it. That means a wrapper class like `Eigen::TriangularView<>`, which is returned by method `.triangularView<>()`. An advantage is that triangular part of the matrix is completely static, so there is no runtime overhead. However implementation would be more complex. We could follow the ideas behind [Eigen's implementation](https://eigen.tuxfamily.org/dox/TopicInsideEigenExample.html) - a templated superclass for `matrix_cl` and `TrinagularViewCL` and then using [Curiously recurring template pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern).

We can also make static triangular part without separate view class. However in that case we can never have in-place operations that would change triangularity.

But we can make everything happen at runtime. This is what most of previous discussion here was about. We simpy add an attribute to `matrix_cl`. Since everything is happening at runtime anyway, I don't think templates make sense in this case.  The overhead would likely be negligible.

To me the second option seems the best.

**Comment by SteveBronder** [comment] 2019-06-12 14:44
> One option I see is following the way Eigen does it. That means a wrapper class like Eigen::TriangularView<>, which is returned by method .triangularView<>(). An advantage is that triangular part of the matrix is completely static, so there is no runtime overhead. However implementation would be more complex. We could follow the ideas behind Eigen's implementation - a templated superclass for matrix_cl and TrinagularViewCL and then using Curiously recurring template pattern.

I like the pattern, but looking at the code for `triangularView` it seems like it might be a big undertaking to go the CRTP route

https://github.com/libigl/eigen/blob/1f05f51517ec4fd91eed711e0f89e97a7c028c0e/Eigen/src/Core/TriangularMatrix.h

Though maybe that's a good idea. We could even think about specific kernels taking the triangular without zeros. Not sure of the effort vs. reward there though

> We can also make static triangular part without separate view class. However in that case we can never have in-place operations that would change triangularity.

That would probs be too hindering

> But we can make everything happen at runtime. This is what most of previous discussion here was about. We simpy add an attribute to matrix_cl. Since everything is happening at runtime anyway, I don't think templates make sense in this case. The overhead would likely be negligible.

> To me the second option seems the best.

I can def agree with the second route. Couldn't we also just template `matrix_cl`? The easiest ways I see rn are

```cpp
// use in signature
matrix_c A(10, 10, triangularity_type = TriangularView::Lower);
// use in template
matrix_cl<TriangularView::Lower> A(10, 10);
```

Though now we have to do `matrix_cl<>` when we don't specify the triangularity. (until we can move to C++17)

One other route if we wanted to go with the templated version above is to start bringing types for the `matrix_cl` i.e.

```cpp
matrix_cl<double, TriangularType::Lower> A(...);
```

I've been working on the `var` and `fvar` specializations of matrix_cl and we can cherry pick out the `double` specialization from [here](https://github.com/bstatcomp/math/blob/feature/matrix_cl-rev/stan/math/opencl/matrix_cl.hpp#L32)

The other piece is dealing with inheritance of triangularity types when doing the math. So 

```cpp
A:Lower + B:Upper -> C:Entire
```

Related to what Sean and I were discussing up [here](https://github.com/stan-dev/math/issues/1198#issuecomment-484071612) do you know of any operations where if `A:triangularity != B:triangularity` then it would not promote to `TriangularView::Entire`?

I think we could use a constexpr function on the template parameters to deduce the above at compile time. I think it would be good to have this all sorted out at compile time because I would worry threading and changing triangularity types in the future.

**Comment by t4c1** [comment] 2019-06-12 15:03
> Not sure of the effort vs. reward there though

At the end that would not be much more code than other options. But it would be harder to write and understand.

> That would probs be too hindering

That was the second option - the one I prefer. If we pick this than `matrix_cl<TriangularView::Lower> A(10, 10); // use in template` is the way to go.

>Couldn't we also just template matrix_cl?

That would only work well with the option that prevents in-place changes to triangularity.

The one you suggest (third) im also ok with. However if we go this way I think we should not pass that in via templates. In other words I like `matrix_c A(10, 10, TriangularView::Lower); // use in signature` with this option, but not `matrix_cl<TriangularView::Lower> A(10, 10); // use in template`

> do you know of any operations where if A:triangularity != B:triangularity then it would not promote to TriangularView::Entire?

Can't think of any.

**Comment by SteveBronder** [comment] 2019-06-12 15:47
> At the end that would not be much more code than other options. But it would be harder to write and understand.

Yes by effort I was mostly talking about maintainability and ease of other developers to add to it. If you don't think it would be hard to bash out a little toy prototype I'd be interested to see it. I like how dumb and simple the current implementation is, though I think it's reasonable to do more adult things

> That was the second option - the one I prefer. If we pick this than matrix_cl<TriangularView::Lower> A(10, 10); // use in template is the way to go.

Ah apologies there was some miscommunication. Why would that stop us from changing the triangularity? I'm pretty sure we could just assign the triangular template value to a member of the class and then change that value as we call new functions. See the link below for an example of what I mean

http://cpp.sh/5tosf

**Comment by t4c1** [comment] 2019-06-12 19:00
If we do things this way than triangularity can change. But I really don't like this option. Let's make it a constructor argument if there is any need to change it.

> If you don't think it would be hard to bash out a little toy prototype I'd be interested to see it.

The more I think about it more it seems like an overkill. I see no need to waste time if we don't have problems with other options.

**Comment by SteveBronder** [comment] 2019-06-13 19:25
> If we do things this way, than triangularity can change. But I really don't like this option. Let's make it a constructor argument if there is any need to change it.

Is the reason you don't like it because of the changing? I can understand that. My link to the toy example is not working for some reason, but when we do the `constexpr` function for example like

```cpp
constexpr the_types change_type(foo& change_me1, foo& change_me2) {
  if (change_me1.type != change_me2.type) {
    return the_types::Entire
  } else {
    return change_me1.type
  }
}
```

The constexpr inlines that code so 

```cpp
matrix_cl<change_type(A, B)> C(10, 10);
```

becomes one of

```cpp
matrix_cl<the_types::Entire> C(10, 10);
matrix_cl<A.type> C(10, 10);
```

I'm fine with doing it as a constructor tho'. Part of me likes doing things at compile time that can be done then. The below is pretty sensible and will probably be easier to implement.

```cpp
matrix_c A(10, 10, triangularity_type = TriangularView::Lower);
```

I think we will also need some method for transpose that flipsthe triangularity. I think for sub_block we want to check that the part we are placing the block into will not disagree with the triangularity we set the original matrix to

**Comment by t4c1** [comment] 2019-06-14 06:14
> Is the reason you don't like it because of the changing?

No. I don't like mixing static (templates) and dynamic (class attribute that can change). That would lead to weird situations where If one wants to create an object with triangularity that is not a compile-time constant. One would have to set some meaningless value to template and than change it immediately.

>  ... will not disagree with the triangularity we set the original matrix to

We can change the triangularity of original matrix.

**Closed** 2019-08-02 07:42 UTC
Labels: code cleanup, gpu
