### ISSUE TITLE
densities for (inverse) Wishart over Cholesky factors

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#43] opened 2015-07-06 21:24 UTC
_From @bob-carpenter on September 19, 2014 21:57_

It would be more efficient to have densities that can be used like

```
cholesky_factor_cov[K] L;
L ~ wishart_cholesky(..,L0);
Sigma <- L * L';
```

Where `Sigma` would then have a Wishart density and `L0` would be the cholesky factor of the parameter. 

_Copied from original issue: stan-dev/stan#1037_

**Comment by syclik** [comment] 2015-07-06 21:24
_From @bgoodri on September 19, 2014 23:25_

This is explained on page 142 on the Stan manual. We just need a C++
implementation that calls normal_log(), chi_squared_log(), and makes an
easy change-of-variables for the diagonal elements.

**Comment by spinkney** [comment] 2022-05-12 10:57
closing duplicate of #2714 and #2710

**Closed by spinkney** 2022-05-12 10:57 UTC
Labels: feature, new function, good first issue
