### ISSUE TITLE
return_type and scalar_type are misleadingly named

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1731] opened 2020-02-20 23:19 UTC
## Description

The result of `return_type_t<T1, ..., TN>` is not, in general, the return type of the function being defined, it's the promotion of all the internal scalars.   It is the return type of an lpdf or lpmf, but we can't generalize to other functions because they don't all return simple real values.  

The result of `scalar_type_t<T1>` is going to be confusing because when we have complex numbers, we're going to pull out the underlying value type (of the real and imaginary components), not the complex scalar itself.

I'm not sure what the right thing is to do here.

#### Current Version:
v3.1.0

**Comment by mcol** [comment] 2020-02-23 19:37
Sounds like a duplicate of #1734.

**Closed by mcol** 2020-02-23 19:37 UTC
Labels: code cleanup
