### ISSUE TITLE
edge probability in Binomial distributions 

### ISSUE THREAD

**Issue by yao-yl** [stan-dev/math#1986] opened 2020-07-26 04:47 UTC
#### Summary:
The edge case in Binomial distributions. 

#### Description:
In most applied modeling, we are using Binomial_logit in the likelihood and the probability will never be 0. However, in certain models, we may encounter exact zero or one probability in a Binomial distribution. 

As expected,  0 ~ binomial(1,  1) leads to log(0). 

However, it seems Stan also cannot handle  1 ~ binomial(1,  1), which indeed should be computed as log 1 in log prob. 

#### Reproducible Steps:
```
log_model='
data {
}  
parameters {
  real<upper=0>  beta;      
}
model {
 1~binomial(1,  exp(beta*0));
}
'
// running in R:
log_fit=stan(model_code =log_model, data=list())
```
#### Current Output:
```
Log probability evaluates to log(0), i.e. negative infinity.
Stan can't start sampling from this initial value.
```

Likewise, when encountered in generated quantities, binomial_lpmf(1| 1,1)  returns NaN.

#### Expected Output:
 binomial_lpmf(1 | 1, 1 ) = 0;

#### Current Version:
v2.23.0

**Comment by rok-cesnovar** [comment] 2020-07-27 06:30
Thanks @yao-yl 

I am transferring this to Math as this is where the code lives and will be fixed.

**Comment by bob-carpenter** [comment] 2020-07-27 15:16
That is the usual edge case for binomial.  

It can cause a lot of trouble for us, because when a logistic regression runs into `inv_logit(a) == 1` or `inv_logit(a) = 0`, it's because the log odds `a` are too large and `inv_logit(a)` rounds to `, or `a` is too small (large and negative) so that `inv_logit(a)` underflows to 0.  

But maybe that should be `inv_logit` throwing the error.  Also, we should really throw errors on `inv_logit` underflow or rounding to 1---we should not try to nudge `inv_logit(a)` just above 0 or just below 1.  Our attempts to do things like that to smooth over the same kinds of issues as led to this issue have led to discontinuous functions and really bad behavior near boundaries.

We also have the same issue with normal, etc.  What happens when sigma -> 0?  should we allow normal(1 | 1, 0) to be 1 (it's now a discrete distribution) or +infinity (as the limit of normal density as sigma -> 0 and y -> mu?  Or should it be an error?  I would argue in that case, it should be an error.

**Comment by yao-yl** [comment] 2020-07-27 19:08
Hi Bob, I think the normal case is a different situation. sigma=0 shifts from a continuous pdf to a discrete pmf. Arguably how to handle discrete measure and continuous measure together remains a general challenge in probabilistic programming lanaguage. 
 
In binomial distribution, binomial_lpmf(1 | 1, 1 ) = 0, or exp(binomial_lpmf(1 | 1, 1 )) = 1,  is well defined, and in agreement with the limit  binomial_lpmf(1 | 1, p ) ->  0 when p -> 1.

**Comment by wds15** [comment] 2020-07-27 19:48
I am relatively sure that the BetaBinomial distribution / cdfs should be checked as well. I am not confident enough to raise another issue for that, but if someone is picking this up, then this would be a bonus thing to do.

**Comment by bbbales2** [comment] 2020-07-27 23:01
I started a pull for this: https://github.com/stan-dev/math/pull/1988

**Closed** 2020-07-29 15:30 UTC
