### ISSUE TITLE
MSVC 2015 Selecting Incorrect erf & erfc Implementation?

### ISSUE THREAD

**Issue by ashmsuhsl** [stan-dev/math#252] opened 2016-03-05 16:57 UTC
**cl version: 19.00.23506
stan version: 2.9.0**

Compiling a model whose generated C++ includes use of stan::math::normal_cdf_log results in this compiler error:

> Error	C2440	'=': cannot convert from 'stan::math::var' to 'T_partials_return'	\stan_math_2.9.0\stan\math\prim\scal\prob\normal_cdf_log.hpp	75	

The problem section of code is:

```
const T_partials_return scaled_diff = (y_dbl - mu_dbl)
  / (sigma_dbl * SQRT_2);

T_partials_return one_p_erf;
if (scaled_diff < -37.5 * INV_SQRT_2)
  one_p_erf = 0.0;
else if (scaled_diff < -5.0 * INV_SQRT_2)
  one_p_erf =  erfc(-scaled_diff);
else if (scaled_diff > 8.25 * INV_SQRT_2)
  one_p_erf = 2.0;
else
  one_p_erf = 1.0 + erf(scaled_diff);
```

MSVC is finding stan::math::erfc and stan::math::erf. 

Adding this:

```
#ifdef _MSC_VER
using boost::math::erfc;
using boost::math::erf;
#endif
```

above the definition of the normal_cdf_log class allows successful compilation. From running two tests, my model seems to be sampling correctly.

Is boost::math::* the correct API call here? std::erf and std::erfc seem to be in scope too.

**Comment by syclik** [comment] 2016-03-05 17:09
Hi Alex,

Are you using CmdStan? Could you provide a simplified version of the Stan
program and how you compiled it? I'll try to reproduce once you send that
over.


Daniel

**Comment by ashmsuhsl** [comment] 2016-03-06 19:46
Hello Daniel,

Yes, I am compiling CmdStan from source. Find a copy of the VS2015 solution here:

http://hslmathsci.org/stan/cmdstan.zip

The model code is in \src. Before trying the build, you will need to edit the Stan.props file and change the paths to point at your local Stan source. I should forewarn you: you will find that the two C2440 error messages are buried in a deluge of warnings - mostly about possible loss of data from conversion of size_t to int, and about unreferenced locals.

Thanks for looking into this. Please let me know if there's anything else I can do to help.

Alex

**Comment by syclik** [comment] 2016-03-11 20:27
@ashmsuhsl you're absolutely right. The error is due to there not being an `erf` and `erfc` in the cmath include. I'll create a pull request for this soon.

**Comment by bob-carpenter** [comment] 2016-08-18 21:09
You're on---I assigned it to you.

**Comment by syclik** [comment] 2016-08-19 15:09
I'll double-check. #134 fixed most of it.

**Comment by bob-carpenter** [comment] 2016-09-02 13:50
This will be taken care of as part of #370

**Closed by bob-carpenter** 2016-09-02 13:50 UTC
Labels: bug
