### ISSUE TITLE
static init order problem

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1306] opened 2019-08-13 10:58 UTC
## Description

Currently, the AD tape initialisation is prone to the static init order catastrophe. This surfaced during the development of PyStan and leads to a segfault.

## Example

The problem is that we require in the `init()` method of `AutodiffStackSingleton` that the pointer to ad instance has been initialised, since we check there if the pointer is equal to `nullptr`. Thus, whenever the pointer to the (optionally thread local) AD tape is not yet initialised, then we run into the static init order problem.

As a solution we need to avoid the double use of the `instance_` pointer. Right now it flags "is not initialised" and it points to the instance we use in the thread when initialised. 

## Expected Output

Our library should not be prone to the static init order problem.

A workaround for C++ users right now is to compile Stan-math with `STAN_MATH_REV_CORE_INIT_CHAINABLESTACK_HPP` being defined. In that case no initialisation is kicked off by our includes. Instead, the C++ user must initialise himself the AD tape at a point in the program when all linked symbols are initialised.

#### Current Version:
v2.20.0

**Comment by riddell-stan** [comment] 2019-08-15 16:16
Thanks for writing this up @wds15. I really appreciate your work on this.

PyStan is particularly affected by this problem because future version of PyStan will *require* STAN_THREADS to be defined. PyStan 3 (via httpstan) is the only interface that supports parallel sampling (e.g., 4 chains) exclusively via threading. RStan, for example, does sampling for different chains in different processes.

Two notes:
- In debugging this problem, I ran into the static init problem even when STAN_MATH_REV_CORE_INIT_CHAINABLESTACK_HPP was defined.
- The workaround PyStan 3 / httpstan is currently using is not really a workaround at all. Since `clang` does not encounter the static init problem, we drop support for gcc on Linux. Since installing clang is not too difficult on linux, this seems ok. More troubling is that neither gcc nor clang work on osx, both segfault. Oddly, gcc works fine on Windows.

**Comment by wds15** [comment] 2019-08-15 20:41
I am sorry that you are hit so hard by this problem, but it hasn't surfaced any where else yet.

I do not understand at all how you can be affected by static init order issues whenever you make that define. In that case it's impossible to have that problem...to my understanding of matters, but I can easily miss details which are Python specific (or something else)?

I am happy to debug myself on the matter, but I would need from you some instructions on what I need to setup and on what branch to look at in order to make progress here. I am on mac, but could run on a Linux as well. Mac is preferred, but if Linux is easier then that.

**Comment by riddell-stan** [comment] 2019-08-15 23:15
You're right. The "static init" problem after I make the STAN_MATH_REV_CORE_INIT_CHAINABLESTACK_HPP define is a bit different. I recall that the segfault occurs in a different place. It occurs when I instantiate the ChainableStack in an thread. It does, however, occur in the same place as the original segfault. Maybe it would be better to call this error a thread-specific static init problem.

**Comment by riddell-stan** [comment] 2019-08-16 17:43
We've (me and @ahartikainen) decided to delay releasing PyStan 2.20 in the hopes that we might be able to fix this problem. I think our main worry is that some people have started using features which require STAN_THREADS (with PyStan 2.19) and abandoning them would be unfortunate.

@wds15 I think it will be easy to get you an environment in which to test things. Have you used Python a fair amount before? (It might be easier if we did this over chat or video conference with chat.)

**Comment by wds15** [comment] 2019-08-17 07:25
I have written Python scripts a long time ago. Right now I am able to modify Python scripts and get my way around with stackoverflow... but I have never done things like coding up extensions for Python. So I would appreciate links to the packages and techniques used to glue things together such that I can search for the right things quickly.

This week is very busy for me, so maybe some pointers get me going already would be good... hopefully things settle then soon - otherwise we can have a video chat, sure.

(It is super odd that things work well on Windows as I understood from your discourse message)

**Comment by ahartikainen** [comment] 2019-08-17 09:37
Maybe we could create a PR, and run tests in travis / locally with suitable script.

**Comment by wds15** [comment] 2019-08-18 16:37
That sounds good to me...just something which I can easily run and get a segfault (locally).

**Comment by riddell-stan** [comment] 2019-08-31 19:07
@wds15 Here's the fastest way to get to the segfault. I believe this should work without any problems (other than the obvious one) on macOS.

I'm using a clean virtualenv, but all this should work even if you don't.

```bash
python3 -m pip install httpstan
```
(This will take a long time, stanc will be compiled)
```bash
python3 -m httpstan
```
Now, in another terminal
```
curl -X POST -H "Content-Type: application/json" \
    -d '{"program_code":"parameters {real y;} model {y ~ normal(0,1);}"}' \
    http://localhost:8080/v1/models
```
This will cause a segfault in the main window. I've verified the segfault is the one we care about:

```
0x00007fffe6a2b258 in stan::math::AutodiffStackSingleton<stan::math::vari, stan::math::chainable_alloc>::init ()
    at ~/.virtualenvs/httpstan-wds15/lib/python3.6/site-packages/httpstan/lib/stan/lib/stan_math/stan/math/rev/core/autodiffstackstorage.hpp:122
122	    if (!instance_) {
```

That should get you started. 

You can modify C++ files which are included in the compilation. For me, they live in the path you can see above: `~/.virtualenvs/httpstan-wds15/lib/python3.6/site-packages/httpstan/lib/stan`

**Comment by wds15** [comment] 2019-09-08 18:06
Hmm... this command you gave me did not work straight, but somehow httpstan runs now and it happily crashes.

Debugging this is a real pain I have to say.

Anyway, I am now trying to modify stan-math. For that I am editing things in

`~/Library/Python/3.7/lib/python/site-packages/httpstan/lib/stan/lib/stan_math/stan/math`

but everything I do there does not seem to have an effect - it always crashes; even things which you told me work (like going back to `thread_local`).

Is it enough to edit the files there or do I need to update something to make the changes become effective or is this thing just crashing so hard on me.

If this all does not help I will have to pull out the c++ which gets generated and try to run it outside of python - the httpstan thing is not very verbose at all (is there a debug mode?).

**Comment by ahartikainen** [comment] 2019-09-08 18:38
Hmm, if it's just headers, then it should work.

I usually do first `git clone` for a local folder, then install from source (locally, called from the `httpstan` main folder)

    pip install -e .

I think you can increase the verbosity adding this at the start of the script (if you are running python script)

    import logging
    logging.getLogger("httpstan").addHandler(logging.StreamHandler())

See https://docs.python.org/3/library/logging.handlers.html

If you are running bash script, then edit line 12 `httpstan/__init__.py` from

    logging.getLogger("httpstan").addHandler(logging.NullHandler())

to

    logging.getLogger("httpstan").addHandler(logging.StreamHandler())

Also you can change the logging level NOTSET / DEBUG

    logging.getLogger("httpstan").setLevel("NOTSET")

https://docs.python.org/3/library/logging.html?highlight=logging#levels

**Comment by wds15** [comment] 2019-09-08 19:28
Thanks. I finally got "a reaction" to my changes. I basically disabled `STAN_THREADS` and then one dummy model seems to sample. Obviously that's not too useful... and this leads me to the question how threads are created in httpstan? Could you point me to the respective code piece?

**Comment by riddell-stan** [comment] 2019-09-08 20:52
@wds15 Thanks for working on this.

re: getting things crashing. If you have things working, that's good. My sense is that the easiest thing to do would be exactly what you suggested, directly edit C++ files in `~/Library/Python/3.7/lib/python/site-packages/httpstan/lib/stan/lib/stan_math/stan/math`. The only trick though is that httpstan caches successfully-compiled models, so you should delete everything in `~/.cache/httpstan` (or `~/Library/Caches/httpstan` on macOS maybe) every time you want to have a fresh compile. (This isn't immediately an issue because the segfault occurs before compilation even counts as successful -- but it will be an issue, I'm sure.)

re: how httpstan works. It's extremely simple at a high level. httpstan is an HTTP server so it responds to HTTP requests. When requests involve sampling, a thread is created and calls ``stan::services::hmc_nuts_diag_e_adapt`` in the thread. The actual thread is created on L69 of httpstan/services_stub.py. (All the complexity in the file is due to the fact that we want to monitor the progress of sampling as it occurs, so we have to pass around the informational messages about what iteration we're on.)

**Comment by riddell-stan** [comment] 2019-09-09 11:30
@wds15 I'm also happy to work on this if you tell me what sort of fixes you would like to try.

**Comment by wds15** [comment] 2019-09-09 11:51
At the moment I am a bit in the dark. I am wondering how things are compiled, so can I see the clang commands being fired off from httpstan?

I would by now try to pull out the cpp files created and setup a program which calls `stan::services::hmc_nuts_diag_e_adapt`. Hopefully that sheds some light on the matter.

**Comment by riddell-stan** [comment] 2019-09-09 16:57
@wds15 this single-commit branch shows you how to un-silence everything: https://github.com/riddell-stan/httpstan/tree/useful-debugging-statements

**Comment by riddell-stan** [comment] 2019-09-13 14:02
@wds15 Do you have a sense of how soluble this problem is? Might it take as long as 3 or 6 months to fix?

I'm wondering if I should put some effort into a one-patch fork of stan-math which will continue to work for pystan. Having a working version of pystan is worth even a significant performance hit.

**Comment by wds15** [comment] 2019-09-13 14:19
I got side-tracked by speculative HMC. Its hard to estimate how long this will take - I plan to attack it once more this weekend.

**Comment by riddell-stan** [comment] 2019-09-13 18:28
@wds15 thanks. Good to know.

I also updated the debug branch I mentioned above. And I grabbed the actual gcc commands themselves in case you just want to read them. This is what I get using gcc and linux:

```
debug views 1
compile_model_extension_module debug 1
_build_extension_module debug 1
Compiling /tmp/httpstan_ekwcnfpv/model_298c809fa2.pyx because it changed.
[1/1] Cythonizing /tmp/httpstan_ekwcnfpv/model_298c809fa2.pyx
building 'model_298c809fa2' extension
creating /tmp/httpstan_ekwcnfpv/tmp
creating /tmp/httpstan_ekwcnfpv/tmp/httpstan_ekwcnfpv
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DSTAN_THREADS -Ihttpstan -I~/work/stan/httpstan/httpstan -I/tmp/httpstan_ekwcnfpv -I~/work/stan/httpstan/httpstan/lib/stan/src -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/eigen_3.3.3 -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/boost_1.69.0 -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/include/python3.6m -c /tmp/httpstan_ekwcnfpv/model_298c809fa2.cpp -o /tmp/httpstan_ekwcnfpv/tmp/httpstan_ekwcnfpv/model_298c809fa2.o -O3 -std=c++1y

....

x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /tmp/httpstan_ekwcnfpv/tmp/httpstan_ekwcnfpv/model_298c809fa2.o -o /tmp/httpstan_ekwcnfpv/model_298c809fa2.cpython-36m-x86_64-linux-gnu.so


.....

{segfault immediately when we try to use this}
```

**Comment by wds15** [comment] 2019-09-14 09:48
No solution yet, but a few observations:

- I modified stan-math to avoid the initialization of the global ad tape
- Then I verified that the unit test `src/test/unit/services/sample/hmc_nuts_diag_e_adapt_test.cpp` does crash as expected
- next, I added a line `stan::math::ChainableStack ad_tape;` into the `hmc_nuts_diag_e_adapt` function which should initialize correctly the ad tape... and it does! The test now runs just fine.

I am not sure what this means. It kind of suggests that thread local pointers are not what they are when things run from Python. As a next step it would be useful to get a hold of the generated cpp files from httpstan. However, I can never access them. Is it possible to get a hold of that?

**Comment by wds15** [comment] 2019-09-14 10:55
I have now taken over your `models.py` so that I can see a little bit of what is going on. Some notes:

- the first compile command is calling a C-compiler, not a C++-compiler -> can this be changed?
- you seem to be using hardening compiler options (-Bsymbolic-functions things). These things are turned on by default from Python => can you disable them?

Finally, I would really like to see the generated c++ files, but its not clear to me how to get them.

This problem appears to be Python specific to me. Some odd way of compilation or some other weird things. At least this is my intuition right now given that things behave as expected when tinkering with stan unit tests.

**Comment by ahartikainen** [comment] 2019-09-14 11:07
Can you fork this function

https://github.com/stan-dev/httpstan/blob/1baafca45e92ab46903eba9ef9116ea391d74bc3/httpstan/models.py#L114

I think python decides compiler at runtime. If we implement our own procedure, we probably could define what compiler should be used.

**Comment by wds15** [comment] 2019-09-14 11:14
I am not sure what you mean with "fork this function". I can insert code into models.py - sure.

**Comment by ahartikainen** [comment] 2019-09-14 11:37
I can check this later.

So fork --> manipulate so it returns cpp code

**Comment by riddell-stan** [comment] 2019-09-14 13:42
>     * the first compile command is calling a C-compiler, not a C++-compiler -> can this be changed?
> 
>     * you seem to be using hardening compiler options (-Bsymbolic-functions things). These things are turned on by default from Python => can you disable them?
> 
> 

The answer here is likely "no" because we're using the standard Python machinery. If there's a bug with this though, reporting it upstream to the Python devs would be extremely valuable since it's likely to affect lots of people. There are *tons* of packages which compile C++ code that then interacts with Python (e.g., Tensorflow, Pytorch).

Also, are you sure that the compiler matters? (I thought clang and clang++ ran the same program, for example).

> Finally, I would really like to see the generated c++ files, but its not clear to me how to get them.
> 

Yes, they land in a temporary directory. The cpp code is generated by Cython and is a little hard to read. I can track down a specific example if it helps.

> This problem appears to be Python specific to me. Some odd way of compilation or some other weird things. At least this is my intuition right now given that things behave as expected when tinkering with stan unit tests.

Knowing whether or not this is an insoluble bug with Python upstream that the 2.20 changes brought into the light would be valuable. If it is, we can report it to the Python devs, of course, but more importantly, we can figure out a fork of stan-math that will work for PyStan. Is there some way of pinning down what is going wrong? I'm happy (well, satisfied) if we pursue this path (rather than trying to fix it). The performance hit of STAN_THREADS in 2.19 wasn't too bad for my workflow.

**Comment by riddell-stan** [comment] 2019-09-14 13:45
@wds15 there likely is some way to change the compile flags (e.g., -Bsymbolic-functions). In the extreme case, we can simply edit the Python source. Let me know if this is worth looking into.

**Comment by wds15** [comment] 2019-09-14 13:49
@riddell-stan I don't get what's wrong here. Like I say, the C++ behaves just I would expect it.

What I would suggest to try:

- Disable these hardening things which are apparently turned on for Python (I also don't know if that's a solution; in fact I doubt it is a solution since I turned these options on with our unit tests and they still work just fine)
- Always compile with C++ compilers and not C compilers (I am not sure it matters, no)
- Attempt to mimic in a basic C++ unit test exactly what Python is doing. So this means to create on macOS a bundle containing the model object code which is then loaded dynamically into another C++ program where it is used. This is the only difference I see between Python and our unit tests.

It is going to be interesting how things turn out in R - the same things happen in R and we yet have to see if STAN_THREADS works there just fine.

(this message is written already in response to some of your comments)

As I say, right now it looks like a Python problem. Somehow the thread local pointer is not anymore existing.

BTW... why can't you use a ProcessPool in Python and disable STAN_THREADS?

**Comment by riddell-stan** [comment] 2019-09-14 14:01
> the first compile command is calling a C-compiler, not a C++-compiler -> can this be changed?

This worked for me:

```
export CC=g++
```
which changed the first compile command to:

```
g++ -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DSTAN_THREADS -Ihttpstan -I~/work/stan/httpstan/httpstan -I/tmp/httpstan_hdlojbcd -I~/work/stan/httpstan/httpstan/lib/stan/src -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/eigen_3.3.3 -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/boost_1.69.0 -I~/work/stan/httpstan/httpstan/lib/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/include/python3.6m -c /tmp/httpstan_hdlojbcd/model_298c809fa2.cpp -o /tmp/httpstan_hdlojbcd/tmp/httpstan_hdlojbcd/model_298c809fa2.o -O3 -std=c++1y
```

Still hit a segfault.

**Comment by wds15** [comment] 2019-09-14 14:12
Maybe this is really a Cython bug and we should try to find a smallish example which shows this?

So it looks to me as if thread_local pointers do not work with Cython. Maybe we create a small Cython example which tries to print a thread-local pointer address? If that segfaults, then this is a Cython bug.

**Comment by riddell-stan** [comment] 2019-09-14 14:59
I like the idea of creating a minimal reproducible example with Cython. This sounds manageable. If you want to suggest a bit of C++ code that has a function in it, I'll write a Cython wrapper for it and try calling the function from Python.

> BTW... why can't you use a ProcessPool in Python and disable STAN_THREADS?

Windows issues. Windows does not play well with ProcessPools. It's a very long-standing issue. Also, although less important, the code is much cleaner with threads on Linux and macOS.

**Comment by riddell-stan** [comment] 2019-09-14 15:04
> next, I added a line stan::math::ChainableStack ad_tape; into the hmc_nuts_diag_e_adapt function which should initialize correctly the ad tape... and it does! The test now runs just fine.

I missed this. This sounds great. I couldn't get this working by editing the Cython code. So you patched the stan services function, simply adding `stan::math::ChainableStack ad_tape;` ?

**Comment by wds15** [comment] 2019-09-14 17:01
Yes, I patched Stan services... but it still segfaults.

I will create a small c++ code which should try to cythenize. Let’s see.

**Comment by wds15** [comment] 2019-09-15 07:36
@riddell-stan could you try to cythenize the `go_spy` function in the little example below. That should lead to a segfault under Cython; it works fine under vanilla C++. Please call that in a similar pattern as in httpstan, so using  a asyncio threadpool thingy to make sure it's all done in a similar environment.

I am curious what the output is. For me the output is

```
thread unit secret is 1
thread unit secret is 10
thread unit secret is 2
```

and sometimes in a different order.

This compiles with `make tls-pattern` for me and runs just fine:
[tls-pattern_cpp.txt](https://github.com/stan-dev/math/files/3613505/tls-pattern_cpp.txt)

**Comment by riddell-stan** [comment] 2019-09-16 17:20
@wds15 no segfault under Cython, https://github.com/riddell-stan/static-init-cython

Here's the output

```
running build_ext
building 'static_init.tls_pattern_wrapper' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/static_init
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Istatic_init -I/usr/include/python3.6m -I~/.virtualenvs/static-init-venv/include/python3.6m -c static_init/tls_pattern_wrapper.cpp -o build/temp.linux-x86_64-3.6/static_init/tls_pattern_wrapper.o
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/static_init
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/static_init/tls_pattern_wrapper.o -o build/lib.linux-x86_64-3.6/static_init/tls_pattern_wrapper.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/static_init/tls_pattern_wrapper.cpython-36m-x86_64-linux-gnu.so -> static_init
before calling go_spy()
thread unit secret is 1
thread unit secret is 2
thread unit secret is 10
done calling go_spy()
```
This currently isn't called exactly the way it is under httpstan. I'll do that next.

**Comment by wds15** [comment] 2019-09-16 18:10
Well, if you can't get it to segfault, then that's good news for sure.

What would also constitute a good toy example to cythenize is the unit test in stan

`src/test/unit/services/sample/hmc_nuts_diag_e_adapt_test.cpp`

I guess any of the tests will do, maybe start with the call_count. However, this is only needed if the go_spy does not segfault when calling the same way as in httpstan (which is through the asyncio threadpool).

I am really curious what the final outcome is by now.

**Comment by riddell-stan** [comment] 2019-09-16 21:03
@wds15 no segfault, aiohttp version https://github.com/riddell-stan/static-init-cython

I'll do the test next, as you suggest.

**Comment by ahartikainen** [comment] 2019-09-16 21:05
Does httpstan call ThreadPool at some point or is it handled by the asyncio?

**Comment by riddell-stan** [comment] 2019-09-16 21:42
It's all asyncio. There's a default ThreadPoolExecutor that gets used by 
`run_in_executor`.

But this reminds me. I should eliminate the parallel sampling part and 
see if it helps things.

**Comment by riddell-stan** [comment] 2019-09-16 22:47
@wds15 FYI: There's a segfault when we use PyStan 2 (which doesn't use threads, or aiohttp). @ahartikainen I have this correct, right?

**Comment by wds15** [comment] 2019-09-17 06:43
If my little example runs ok in asyncio, then it should be possible to run things with STAN_THREADS.

The ultimate test is the unit test which then runs exactly the same code as you do during httpstan calls to the services API.

As there is a segfault with Python 2: This is interesting, hinting at the trouble; but I am not sure if this matters to you nor is it clear why Python 2 has trouble as opposed to Python 3.

Anyway - let's see what the unit test does.

**Comment by ahartikainen** [comment] 2019-09-17 06:51
> As there is a segfault with Python 2: This is interesting, hinting at the trouble; but I am not sure if this matters to you nor is it clear why Python 2 has trouble as opposed to Python 3.

PyStan 2 vs PyStan 3 (yeah, I know, this is nitpicking :) )


> @wds15 FYI: There's a segfault when we use PyStan 2 (which doesn't use threads, or aiohttp). @ahartikainen I have this correct, right?

Yes PyStan 2 uses multiprocessing.map if n_jobs>1. Does PyStan2 crash with STAN_THREADS and n_jobs=1?

Can we add some `std::cout` calls to see at what "step" the code segfaults? With one thread this would probably work ok?

**Comment by riddell-stan** [comment] 2019-09-17 12:51
You're right. I forgot to turn on STAN_THREADS. Sorry. Forget everything 
I said. I'll re-run things today.

**Comment by riddell-stan** [comment] 2019-09-22 14:21
@wds15 I created a minimal example without any run-time compilation. I can't get the example to segfault but it might be worth trying on another platform, especially macOS. Here's the repo: https://github.com/riddell-stan/python-cython-stan-test

**Comment by riddell-stan** [comment] 2019-09-22 21:21
@wds15 @ahartikainen I'm also thinking that we should prepare for the possibility that this might not be fixed by 2.21. @wds15 are there any obstacles to creating a one-commit fork of stan-math which returns to the older (slower) version which does not crash pystan? If we have such a fork, we could at least release PyStan 2 2.20 (with optional STAN_THREADS) and httpstan 2.20. I don't think there's a single person who will be bothered by the performance slowdown since nobody ever got used to the faster version.

**Comment by wds15** [comment] 2019-09-23 14:02
@riddell-stan Well, it's good news to me that you cannot break the minimal examples...which suggests that there should be a way forward here. Could you quickly give an overview of what you tried and what works/doesn't work? Thanks.

I am happy to try out on macOS your minimal python examples. Is everything run in a single go or are there some instructions to follow (just super basic ones).

I think you have already reverted the PR which does this change - so it seems possible to deploy a 2.20 PyStan which uses the old scheme...but certainly document that well!

As we are moving towards using the Intel TBB there is actually hope that all of these troubles go away by transitioning to the TBB threadpool. The TBB managed threadpool will initialise the required AD reverse mode AD tape resources itself. So with luck all troubles go away. Depending on the progress we will have TBB in 2.21, the latest in 2.22.

Still, resolving this mess would be great... however, maybe now is a good time-point to move this thread to a PyStan or httpstan repo issue, no? Looks to me that the culprit is not in Stan-math.

**Comment by riddell-stan** [comment] 2019-09-23 14:46
If you're certain that TBB will be used in the future, then this 
definitely can be closed (since it will be obsolete).

Glad to know there aren't any big obstacles to a one-commit fork. I'll 
likely create it under my username and invite you to look at the pull 
request.

**Comment by wds15** [comment] 2019-09-23 15:59
I can look at that pr, sure.

However, the tbb may solve things, but maybe not. The thing is that the errors I saw so far suggest that the tls pointer does not exist...but with some luck this is about some ordering problem which is solved by using the tbb. Let’s see.

**Comment by riddell-stan** [comment] 2019-09-23 20:12
@wds15 Do you mind seeing if you can get things to segfault on macOS? It should only take a second. If it does segfault we have a very easy path to figuring out what is wrong.

https://github.com/riddell-stan/python-cython-stan-test

Just run the two commands in the README.

**Comment by riddell-stan** [comment] 2019-09-23 20:13
Starting to work on a clean one-commit fork now. There's a provisional PR open here: https://github.com/riddell-stan/math/pull/1

**Comment by ahartikainen** [comment] 2019-09-23 20:48
Do we still have a problem with GCC on linux?

**Comment by riddell-stan** [comment] 2019-09-23 20:56
With STAN_THREADS, yes. Everything segfaults for me if I use gcc.

**Comment by wds15** [comment] 2019-09-23 21:41
I am traveling and will try on macOS the coming weekend.

**Comment by wds15** [comment] 2019-10-15 18:14
@riddell-stan so, I did run the two commands on macOS Mojave using clang and I am seeing "success".

I have to say that in the meantime my Xcode went to version 11 and I have this version string now:

```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I am still on Mojave.

Sorry for having dropped the ball, but getting the TBB into 2.21 had prio.

Maybe we should attempt to work on getting 2.21 to work straight...given that the TBB could solve all of this? In any case, we should move to another issue which is PyStan specific.

**Comment by riddell-stan** [comment] 2019-10-17 16:03
@wds15 I should be able to test things after 2.21 is released. (Although getting httpstan to build in a non-header-only way is going to take a fair amount of time.)

**Closed** 2019-11-21 16:16 UTC

**Comment by wds15** [comment] 2019-11-21 16:41
@riddell-stan this is in now... but I doubt that it solves your issues. The actual problems are along the lines of what we did for Rstan.

**Comment by riddell-stan** [comment] 2019-11-21 21:16
Thanks. Is there a summary somewhere of what fixed the problem?

**Comment by wds15** [comment] 2019-11-21 22:04
Not really... I don't blog this... but this:

https://discourse.mc-stan.org/t/future-rstan-is-broken-with-clang/11676/19?u=wds15

lead me to the solution. Basically you need to ensure that nothing of the AD tape global stuff gets compiled into the services. The AD tape global things must be linked into the model which then gets loaded dynamically into the R process where the stan model services are already available from a dynamically loaded shared library which contains the services. That's how I understand it.

**Comment by riddell-stan** [comment] 2019-11-22 16:44
Thanks for the note. (The blog you link to in the thread is helpful, 
https://techunravel.blogspot.com/2011/10/staticglobal-variable-and-shared.html 
)

Is everything fixed in the RStan repo right now? (That's where I would 
look for instructions on how to "ensure that nothing of the AD tape 
global stuff gets compiled into the services") Is there anything that 
will need to be changed as a result of this PR or for Stan 2.22 generally?

**Comment by wds15** [comment] 2019-11-22 19:58
Yup, the blog is what lead me to the solution.

Rstan works by now with 2.21 just fine. The working branch is on the "for_2.20" branch of rstan. We are about to file RStan to CRAN (what is making this a length process is the CRAN requirements to keep all dependent packages in a working state - even though these dependent packages become outdated wrt how to link & compile against stan 2.21)

The fix in the respective PR for this issue is probably only cosmetic, but it definitely improves matters as the code was prone to static init order catastrophe which we avoid now.
