### ISSUE TITLE
threading on linux with clang

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#820] opened 2018-04-07 08:26 UTC
#### Summary:
Threading on linux + clang is broken in most linux distributions, but can be fixed.

#### Description:
Most linux + clang configurations will not be able to turn on threading in `stan-math` as they run into [this issue](https://stackoverflow.com/questions/29322666/undefined-reference-to-cxa-thread-atexitcxxabi-when-compiling-with-libc#30437761). It would be great to automatically detect whenever the solution mentioned on stackoverflow works and if so link it in automatically. Very likely this is linked to the libc++ version used. If libc++ >= 4.0 is used, then things should work out of the box, but this needs to be verified.

#### Reproducible Steps:
On linux with a clang compiler do
0. use clang on linux
1. enable threading, see [here](https://github.com/stan-dev/math/wiki/Threading-Support)
2. `./runTests.py test/unit/math/rev/mat/functor/gradient_test.cpp`

#### Current Output:
This won't link

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
develop, 7th April 2018

**Comment by sakrejda** [comment] 2018-04-29 21:39
This issue is mis-named but would be good to get this fixed.  The configuration actually works if you change make/detect_default_cc (as below).  So the issue is linux + clang + libc++ (some versions!).  On my Ubuntu installing the default packaged libc++ actually fails to build our tests unless I modify some headers in libc++ (to stop pretending like libc++ has xlocale suport and a cxxabi compatability header).  

I know there are "reasons" why -stdlib=libc++ was added for clang++ but they've never been specified and we don't know if they're still relevant so I'd say fix this by dumping libc++ from the default config.

.. @syclik @seantalts do you recall the reason why this `-stdlib` switch is so broad?  If the real reason is lost to history can we try changing it and see who complains? It's irritating to have to keep hacking things to make Ubuntu + clang work with Stan.


```
krzysztof@fit:~/packages/stan-math-threads$ git diff
diff --git a/make/detect_cc b/make/detect_cc
index fd899cd1b4..104ce0a987 100644
--- a/make/detect_cc
+++ b/make/detect_cc
@@ -10,7 +10,6 @@ ifneq (,$(findstring clang++,$(CC)))
   # To deal with that we force it to use llvm's bundled libc++ replacement for
   # gcc's stdlibc++ here. Plus it's better to rely on just one compiler if we
   # can.
-  CXXFLAGS += -stdlib=libc++
 endif
 ifneq (,$(findstring mingw32-g++,$(CC)))
   CC_TYPE ?= mingw32-g++
```

**Comment by sakrejda** [comment] 2018-04-29 21:40
Oh right, the comment does reference Travis, but Travis is not something I can fix.  Tell me what fails on Travis and we have a real to work on.  Or put a make/local as part of the Travis config and stop having an old Travis bug drive our development.

**Comment by wds15** [comment] 2018-05-01 14:55
I think you are right in that we should not enforce to use libc++ whenever clang++ is used - rather we should use whatever is the default of the clang++ we are using.

I haven't set this up, but I am guessing that the rationale behind the setting is that on Travis we need to force clang++ to use libc++ via this option. The reason to push clang++ into the direction of libc++ is probably that libc++ is recommended over libstdc++ for use with clang++. Now, that is obviously not a super good recommendation as we are discovering.

I would argue that we should not specify the `-stdlib` option for clang++ such that it will use the default used to build the compiler (whatever that is). This should give us the best outcome in terms of system compatibility, etc.

@seantalts or @syclik Any thoughts?

**Comment by rok-cesnovar** [comment] 2019-10-15 12:38
I am assuming this is irrelevant with TBB now. No issues on Linux + clang or g++. Closing.

**Closed by rok-cesnovar** 2019-10-15 12:38 UTC
