### ISSUE TITLE
How do do rep_matrix(scalar, rows, cols) for var matrix?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2344] opened 2021-01-31 05:19 UTC
## Description

Looking at the code for `rep_matrix` I'm kind of confused about how to do this for the new matrix type

```cpp
template <typename T, require_stan_scalar_t<T>* = nullptr>
inline auto rep_matrix(const T& x, int m, int n) {
  check_nonnegative("rep_matrix", "rows", m);
  check_nonnegative("rep_matrix", "cols", n);
  return Eigen::Matrix<return_type_t<T>, Eigen::Dynamic,
                       Eigen::Dynamic>::Constant(m, n, x);
}
```

There's no information in the signature on whether it should be a var matrix or matrix var. I'm not really sure how to handle that in the language?

**Comment by rok-cesnovar** [comment] 2021-01-31 15:45
We have the same issue for `matrix_cl` overloads for all signatures that have scalar-only args but output an Eigen-type. 
For varmat there are additionaly also signatures with scalar/scalar-array only arguments.

```
matrix identity_matrix(int)
row_vector linspaced_row_vector(int, real, real)
vector linspaced_vector(int, real, real)
row_vector one_hot_row_vector(int, int)
vector one_hot_vector(int, int)
row_vector ones_row_vector(int)
vector ones_vector(int)
matrix rep_matrix(real, int, int)
row_vector rep_row_vector(real, int)
vector rep_vector(real, int)
row_vector zeros_row_vector(int)
vector zeros_vector(int)

// only a problem for varmat
matrix to_matrix(int[], int, int)
matrix to_matrix(int[], int, int, int)
matrix to_matrix(real[], int, int)
matrix to_matrix(real[], int, int, int)
matrix to_matrix(int[,])
matrix to_matrix(real[,])
row_vector to_row_vector(int[])
row_vector to_row_vector(real[])
vector to_vector(int[])
vector to_vector(real[])

// for matrix_cl its also this one
int[] zeros_int_array(int)
```

 We talked about this with @t4c1 and we narrowed it down to these options: 

1. add a template to these functions. The type determines the output type
    
    Probably the cleanest solution in a vacuum, but would break backwards compatibility as `rep_matrix()` would no longer work as before. Though this only requires a bump in Math.

2. add `prefix_`/`_suffix`

    For example `rep_matrix_varmat()` or `varmat_rep_matrix()`. No backward compatibility issues. But would require stanc3 to either disallow these prefixes/suffixes for all functions or just these function. The latter complicates the stanc3 code with yet another list of functions to keep track of. The former is a bit restrictive, though I guess `rep_matrix_varmat` is not a common name someone would use. 

3. add `prefix__`/`__suffix`

   Since __ is restricted in Stan language this adds no additional restrictions. Its a bit of an ugly name for functions, but 2. isnt much better in that regard.

**Comment by bob-carpenter** [comment] 2021-01-31 17:35
For (1), can't we add a template with a default to not-a-varmat?   

The bigger issue is what to do in the language.  I'd rather not introduce the language "varmat", which is very implementation specific.  Can we call it something like "immutable"?  I know there is some code to make them modifiable, but I think that's both confusing and not something we want to encourage in performant Stan code.   Has the decision already been finalized to allow these things to be modified once constructed?

**Comment by rok-cesnovar** [comment] 2021-01-31 18:03
> For (1), can't we add a template with a default to not-a-varmat? Or would we still need <> in the no-template args case? If so, we can add the template version, and then implement the original version to delegate to the appropriate template and then deprecate the original version.

That make sense.

> The bigger issue is what to do in the language. I'd rather not introduce the implementation-specific type "varmat". Can we call it something like "immutable"? I know there is some code to make them modifiable, but I think that's both confusing and not something we want to encourage in performant Stan code. I'd prefer to see a mutable matrix created and assigned to an immutable one which then remains immutable. Though I really believe the best solution will be comprehensions.

The current plan that is ongoing is that the language will have no notion of varmat, this is compiler-internal stuff what we are talking about here (see link below).
So the user would still call `rep_matrix()` in Stan but the compiler would actually use `rep_matrix<var_Value<Eigen::MatrixXd>()` or `rep_matrix_varmat()` *if applicable*.

> Has the decision already been finalized to allow a varmat type to be modified once constructed? 

No, that is not plan at the moment. You can read the current plan [here](https://github.com/stan-dev/design-docs/blob/master/designs/0005-static-matrices.md#stanc3-implementation). This is what we plan for 2.27 but this can obviously change if someone comes with a better plan.

The current plan is intentionally conservative as while the goal number 1a is performance, goal 1b is no regression and this approach guarantees that.

> Is this the kind of thing that requires a vote in the process now?

I guess anything is up for a vote if someone wants it. I think that is the idea.

**Comment by SteveBronder** [comment] 2021-01-31 21:06
It looks like (1) is viable / backwards compatible

https://godbolt.org/z/x7TY7Y

So we could just have a default template parameter

**Comment by rok-cesnovar** [comment] 2021-02-26 11:42
This was resolved by going with rep_matrix<var_Value<Eigen::MatrixXd>()

**Closed by rok-cesnovar** 2021-02-26 11:42 UTC
