### ISSUE TITLE
Implement SSfoo functions from R

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#144] opened 2015-08-14 04:23 UTC
Running `example(selfStart)` in R ultimately lists 10 transformation functions

```
List of 10
 $ SSasymp    :function (input, Asym, R0, lrc)  
 $ SSasympOff :function (input, Asym, lrc, c0)  
 $ SSasympOrig:function (input, Asym, lrc)  
 $ SSbiexp    :function (input, A1, lrc1, A2, lrc2)  
 $ SSfol      :function (Dose, input, lKe, lKa, lCl)  
 $ SSfpl      :function (input, A, B, xmid, scal)  
 $ SSgompertz :function (x, Asym, b2, b3)  
 $ SSlogis    :function (input, Asym, xmid, scal)  
 $ SSmicmen   :function (input, Vm, K)  
 $ SSweibull  :function (x, Asym, Drop, lrc, pwr) 
```

that are often used in PK / PD models, which we will need if we want to write a `stan_nlmer` function that is similar to `lme4::nlmer`. These are relatively easy to implement because these R functions also calculate the gradient with respect to all arguments except the first and return it as an attribute of the output. Just execute `body(SSfoo)` to see the R implementation.

**Comment by bob-carpenter** [comment] 2015-09-15 16:32
Where do these go?  Are they going to be functions exposed in the Stan language?

We should define the math first and then implement them from scratch to avoid any IP issues with GPL-ed code.

**Comment by bgoodri** [comment] 2015-09-15 17:49
Rayleigh is working on this. Yes, they should be defined first in Stan
Math, then exposed in the Stan language, doc'd etc. The FSF doesn't think
of translating a simple mathematical function from one language to another
as a derived work.

**Comment by rayleigh** [comment] 2015-10-02 20:02
Moving the conversation over from email where we've been talking about organization and what is needed.

Do we need a version for these functions with a scalar input? If they're all link functions for non-linear regressions, such as SSasymp, the results don't seem meaningful if called with one value.

Also, I've been assuming the other parameters, such as Asym, R0, lrc, are scalar, because that's how it's implemented in R. Is this a safe assumption?

**Comment by bgoodri** [comment] 2015-10-02 20:50
I think the vast majority of the time people would call these functions
with a vector as the first argument and scalars for the remaining
arguments, but we do need versions for any combination of scalars and
vectors, inclusive of all scalars and all vectors. This really doesn't add
that much to the coding burden because every other function should just be
calling the all scalar function at every iteration of its loop over the
vectors.

**Comment by bob-carpenter** [comment] 2015-10-02 21:58
It actually adds a lot to the coding burden because
of the combinatorics of testing.

Do you really need every argument to possibly be a vector?
If so, what's the return type?  How is the function defined
for vectors other than in the vectorized position in the R code?

- Bob

**Comment by bgoodri** [comment] 2015-10-02 22:04
It wouldn't make sense for the first argument to be a scalar and any of the
subsequent arguments to be a vector. It would make sense for the first
argument to be vector-like and any of the subsequent arguments to be a
scalar or vector-like with the same length as the first argument like we do
for sampling statements (except a vector-like thing would be returned). We
could probably write a test-generating function like we do with the
densities. But it is fine to start with the case where the non-first
arguments are scalars and get that one working.

**Comment by bob-carpenter** [comment] 2015-10-03 20:36
They're rather different implementation paths, I think,
between writing a simple function and a vectorized density
The former is simple and the latter really needs to use all
the traits and expression template stuff we have in place.

Is the one that takes multiple vector arguments just
returning a single value?  Is the one taking vector
arguments in the first position returning a single value?
I'm not entirely clear what signatures are under discussion here.

If they don't combine into a single value, then the implementation
is going to be different again, because we don't return a single
constructed autodiff var, but many.  So it's fewer of the moving
pieces.  For efficiency, I doubt they'll just loop over the
scalar functions, but we could do that to start.  

I've been thinking about general patterns for vectorization, but
it'd require writing the unary version as a functor and then
passing that functor's type to helper functions.  I have it worked
out, but it'd need to be implemented.  But for 10 functions with
lots of arguments that are just distributed, it might be worth it.
And it'd let us easily vectorize what's left of the functions
in Stan, too.

Rayleigh also said that one of the functions is a density
(Gompertz, I believe).  So that should be implemented like our
other ones.  And should ideally include CDFs and RNGs, but it's
not a hard requirement.

Is there a priority order for these or is it all or nothing?

- Bob

**Comment by bgoodri** [comment] 2015-10-03 23:24
The number one priority signature is to input a var vector and a few var scalars and output a vector. But if we implemented it with VectorViews, then some mix of vectors and scalars wouldn't require extra implementations.

The Gomperz density is different from the Gompertz transformation function
https://en.wikipedia.org/wiki/Gompertz_distribution#Probability_density_function
https://en.wikipedia.org/wiki/Gompertz_function#Formula

**Comment by bob-carpenter** [comment] 2015-10-04 19:53
> On Oct 3, 2015, at 7:24 PM, bgoodri <notifications@github.com> wrote:
> 
> The number one priority signature is to input a var vector and a few var scalars and output a vector. But if we implemented it with VectorViews, then some mix of vectors and scalars wouldn't require extra implementations.

If we need all those variants then this is the only
way to go.  If there aren't custom derivatives, it's
not much harder.  If there are, then it has to all
be done like the densities.

Do all the functions just distribute through the
different positions?  So that there's an underlying
scalar function like f(a,b) and the vectorized form
f(av, bv) is just (f(av[1],bv[1]), ..., f(av[N], bv[N]))
And if av or bv is a scalar, it's just broadcast for
reuse in every position.

That's what I think is worth somehow metaprogramming.
I don't think it'll be too hard without custom derivatives.
As soon as there are custom derivatives, then you need to
think about which intermediate things to cache.

> The Gomperz density is different from the Gompertz transformation function
> https://en.wikipedia.org/wiki/Gompertz_distribution#Probability_density_function
> https://en.wikipedia.org/wiki/Gompertz_function#Formula

And this is just the transform?

- Bob

**Comment by rayleigh** [comment] 2015-10-14 22:01
For the first current version of SSfoo, can I just implement the following:

SSfoo(std::vector<T1>& input, T2 param1, T3 param2, etc.) 

which returns a std::vector of the boosted type that is the same length as input?

Also, are there certain functions that you want out of the 10 functions?

Finally, how are you planning on use these functions? I understand that it's used as a link function for a nlmer call in R so is it something that'll be used by Rstan arm code primarily? If so, how will it be used there?

**Comment by bob-carpenter** [comment] 2015-10-14 22:14
I think the main issue here is whether we can write these things with specialized signautres that have double values rather than having everyting flexible enough to enter into Stan's language?  If it has to go into the language, we'll have to make everything polymorphic.

**Comment by bgoodri** [comment] 2015-10-16 06:22
We want to be able to do models like these

http://lme4.r-forge.r-project.org/slides/2010-05-26-Muncie/slidesD.pdf

It would suffice to start by implementing all the SSfoo() functions in Stan
assuming var for everything except the output and the first input is a var
vector. But ultimately I think they are going to have to get implemented
like the densities, except returning a var vector rather than a var scalar.

**Comment by bob-carpenter** [comment] 2015-10-17 22:03
OK --- that's a lot of work in testing for a four-element
function if we're going to be rigorous like we're doing now.
It either means generalizing or building a paralell testing
framework to the densities due to return value.

I've been tinkering with some template-based list approaches
to dealing with this that I think are promising.

The question is whether we need them exposed in the language, or
whether it'd be enough to have them in the math libs.

The second question is breadth vs. depth.  Is it better to get
limited versions (in terms of efficiency and generality of
arguments as var and vector) of them all, or do one all the way
through to start?

- Bob

**Comment by bgoodri** [comment] 2015-10-17 22:28
I think they would need to be exposed in the Stan language, even if they
are initially unlikely to be used outside of a .stan file in a future
rstanarm. Thusfar, we haven't added any hacks to rstanarm that would enable
it to do things that a motivated user couldn't do ordinarily with the Stan
language, and I would rather keep it that way.

So, it would be fine to start with something like

vector SSfoo(vector, real, real, real) {
  // implementation
}

so that in a few months we could write a stan_nlmer() function that would
enable us to do what lme4 can do now:

nm1 <- nlmer(circumference ~ SSlogis(age, Asym, xmid, scal) ~ Asym|Tree,
             data = Orange, start = startvec)

But it may be more total work to do a limited implementation of the SSfoo
functions now and do a complete reimplementation later.

**Comment by bgoodri** [comment] 2016-03-04 22:35
I think this is a long way off, so closing.

**Comment by syclik** [comment] 2022-01-12 02:36
Closing again.

**Closed by syclik** 2022-01-12 02:36 UTC
Labels: feature, wasn't fixed
