### ISSUE TITLE
recover_memory called without corresponding check of empty_nested

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1316] opened 2019-08-16 10:39 UTC
https://discourse.mc-stan.org/t/stan-memory-management/10275

EDIT: More complete description

There are currently many unit tests which call `recover_memory` without checking `empty_nested`. When empty_nested is false, these calls throw an exception, causing the tests to fail. These include the following source files: 

mat/functor/idas_integrator_test.cpp
rev/mat/functor/cvodes_ode_data_prim_test.cpp
rev/mat/functor/cvodes_ode_data_rev_test.cpp
rev/mat/functor/integrate_dae_test.cpp
rev/mat/fun/append_row_test.cpp
rev/mat/fun/append_col_test.cpp
rev/mat/fun/matrix_exp_multiply_test.cpp
rev/mat/fun/gp_periodic_cov_test.cpp
rev/mat/fun/gp_exp_quad_cov_test.cpp
rev/mat/fun/cov_exp_quad_test.cpp
rev/mat/err/check_consistent_sizes_test.cpp
rev/mat/err/check_pos_semidefinite_test.cpp

When aggregating these unit tests into a single binary, an exception is thrown since the memory arenas are not able to be properly reclaimed.

I was advised to post this here by @wds15

**Comment by syclik** [comment] 2019-08-16 13:13
@alashworth, would you mind posting a complete issue description? I know it's a bit redundant, but having a description of the issue is useful.

**Comment by rok-cesnovar** [comment] 2019-08-29 19:06
@alashworth What is the easiest way of reproducing this? Use the monorepo? What do I need to run then?

I tried joining `rev/mat/fun/append_row_test.cpp` and `rev/mat/fun/append_col_test.cpp` and running `runTests.py` but could not reproduce the throw from `recover_memory()`. Would love to help if this is a blocking issue for you but first need a way of reproducing.

**Comment by alashworth** [comment] 2019-09-03 10:04
@rok-cesnovar  Ah, no worries then; no need to pull you away from your current work. I'll fix it myself in the monorepo - I left the issue here because wds15 mentioned that he might have wanted to fix it himself here.

**Comment by rok-cesnovar** [comment] 2019-09-03 10:48
Ok, thanks. Closing the issue then, re-open anytime if you feel this should be fixed in Stan Math directly.

**Closed by rok-cesnovar** 2019-09-03 10:48 UTC
