### ISSUE TITLE
Adding 7-Parameter Drift Diffusion Model (DDM) PDF with partial derivatives to Stan Math

### ISSUE THREAD

**Issue by Franzi2114** [stan-dev/math#2682] opened 2022-03-02 12:39 UTC
## Description
The Drift Diffusion Model (DDM) introduced by Ratcliff provides a framework for analyzing data of fast binary decisions jointly modelling accuracy and response times. There are several parameterizations of the DDM. Currently Stan Math contains the PDF of the 4-parameter variant (i.e., the parameters for threshold separation, non-decision time, relative starting point, and drift rate) in the function wiener_lpdf(). Furthermore, @kendalfoster is working on a 5-parameter variant of the DDM (i.e., including the parameter for inter-trial variability in the drift rate) (see issue #2584) 

I am working on a pull request to add a 7-parameter variant with partial derivatives of the DDM (i.e., additionaly including the parameters for inter-trial variabilities in relative starting point and non-decision time). For this goal, I first want to implement the lpdf and lcdf of the 4-parameter model `wiener4_lpdf` and `wiener4_lcdf` containing partial derivatives. In the next step, I want to use these functions to expand the model to a 7-parameter model containing partial derivatives `wiener7_lpdf` and `wiener7_lcdf`. These `wiener7` functions will be built in the way that they call the `wiener4` functions for the case that all three variability parameters are set to 0.  Almost all computations are done on the log scale which makes computations more stable. All functions will be based on the implementation of the R-package WienR by @RaphaelHartmann. (Therefore, checks whether the correct values are computed can be done via the WienR package in R).
 
The 4-parameter functions will accept the following parameters: response time,  threshold separation, drift rate, relative starting point, non-decision time, precision, response.

The 7-parameter functions will accept the following parameters: response time,  threshold separation, drift rate, relative starting point, non-decision time, inter-trial variability drift rate, inter-trial variability relative starting point, inter-trial variability non-decision time, precision, response.

(There may occur minor changes in the parameter lists).

The idea is to implement the 7-parameter model in the way that it also can be used as a 4-, 5-, or 6-parameter model. For this, the user only has to set the corresponding variabilities to 0.

## Example
4-parameter model:
An example call to the lpdf is `wiener4_lpdf(1, 1, -1, .5, .1, .01, 1)` and would return the log of the PDF.
An example call to the lcdf is `wiener4_lcdf(1, 1, -1, .5, .1, .01, 1)` and would return the log of the CDF.

7-parameter model
An example call to the lpdf is `wiener7_lpdf(1, 1, -1, .5, .1, .5, .6, .7, .01, 1)` and would return the log of the PDF.
An example call to the lcdf is `wiener7_lcdf(1, 1, -1, .5, .1, .5, .6, .7, .01, 1)` and would return the log of the CDF.

## Expected Output
We should expect the example call to `wiener4_lpdf(1, 1, -1, .5, .1, .01, 1)` to return `-4.24659 `.
We should expect the example call to `wiener4_lcdf(1, 1, -1, .5, .1, .01, 1)` to return `-1.323102`.

We should expect the example call to `wiener7_lpdf(1, 1, -1, .5, .1, .5, .6, .7, .01, 1)` to return `-1.90939`.
We should expect the example call to `wiener7_lcdf(1, 1, -1, .5, .1, .5, .6, .7, .01, 1)` to return `-1.289187`.

## Edit
In a first step, I want to implement `wiener_full_lpdf`. This function will be able to compute a 4-, 5-, 6-, and 7-parameter model. So: `wiener4_lpdf` and `wiener7_lpdf` will be parts of `wiener_full_lpdf`. The cdf function will be postponed.

## Second Edit
The 7-parameter model `wiener_full_lpdf` is now implemented. We do not implement the 4-parameter model seperately and we also do not implement the CDF functions. The 7-parameter PDF functions are now in the testing phase and will soon be availabe.

## Open Questions
I already started the implementation. There are still some open questions:
- [x] How to handle the precision?  ([see this Discourse thread](https://discourse.mc-stan.org/t/fix-the-precision-or-let-it-vary/26255))
* Set the precision to a fixed value?
* Or let the user set a precision and set a default for the case the user does not give a precision?
* Then: How to implement a default value? Or if-statement whether the user set 0 and then internally set the precision?
- [x] How to compute a multidimensional integral? ([see this Discourse thread](https://discourse.mc-stan.org/t/is-there-a-multidimensional-integrate-function/26404))
* At the moment I am working on a solution to use hcubature or a similar routine.
* **Edit** To incorporate the other two inter-trial variabilities I have to integrate over two variables. Therefore, I need to compute two bounded integrals to obtain the 7-parameter PDF. Is there a way to compute these integrals in Stan? 
* Is there a way to translate the GPLv2+ hcubature into Stan-style and use it in BSD3 Stan-math?
* Can I somehow combine Julia with Stan?
- [x] How to organise the file? ([see this Discourse thread](https://discourse.mc-stan.org/t/adding-a-function-with-large-known-partial-derivatives/26254)) 
* As the computation of the derivatives is quite long, I compute the derivatives outside the lpdf function in an extra function. Shall I let the functions for the derivatives in the same file as the lpdf or save them in additional files? Then: Would stan/math/prim/prob be the correct spot to save the derivatives?
- [x] When do I need the `bool<propto>`?
- [x] How to deal best with responses?
* In the DDM there are two response options: Upper bound = 1, lower bound = 0. The current `wiener_lpdf` only computes the lpdf for upper bound responses. For the lower bound responses the user has to change the input data. But it is also possible to give the response as a parameter to the function and then choose the upper/lower bound model internally. Do you have suggestions/pros/cons?
- [x]  **Edit** Now, the functions for `wiener_full_lpdf` are almost ready for the pull request. Which tests and steps do I have to do before I send the pull request? Can anybody give me a list or a link where I find everything?

#### Current Version:
v4.3.0

**Comment by bob-carpenter** [comment] 2022-03-02 16:26
Thanks, @Franzi2114.  I can help with some of the questions:

* if there's a variable precision algorithm that's really costly as precision goes up, then the most friendly API makes its user-controllable with reasonable defaults;  usually we try to hit 5 or 6 digits at least, as we've found less than that won't work with our ODE solvers (of course, this depends if the error control is stepwise or global);  the best thing to do is run some experiments with typical values

* I have no idea bout hquadrature, but the usual bottleneck for ay quadrature algorithm is dimensionality;  is this something that could be evaluated with nested MCMC (we don't have a way to do that with HMC at the moment)

* helper functions can go in the same file and should be placed in namespace `stan::math::internal`

* when `propto` is true (1), you can drop constants in the log density that don't depend on any of the autodiff variables (all parameters will be autodiff variables), as they don't matter to Stan's HMC algorithm for sampling

* as for the response options, I'd suggest two different functions rather than one with a flag;  then you can have a reasonable default with no extra args and then one marked with a suffix like `_upper`.  Or, if the user can workaround with data transforms, it makes sense to only implement one

**Comment by Franzi2114** [comment] 2022-09-27 14:00
Hi, I have two more questions:

> with reasonable defaults

@bob-carpenter, how is the way to define defaults for our new function? Is it related to the Stan_math_signatures.ml or is it in the definition of the function itself?

The function is now nearly finished and ready for a pre-publication. I first want to add a new branch with this feature in Stan/math and not make a Pull Request to the develop branch at the moment. This shall come a bit later. How can I add a new branch to Stan/math without writing access?

Best,
Franzi

**Comment by bob-carpenter** [comment] 2022-09-29 12:10
Sorry for not answering sooner, but I've been traveling.

> how is the way to define defaults for our new function?

Stan doesn't have a notion of default arguments or of named arguments.  Every argument to a Stan function is required.  What we've done with things like the ODE solver is provide two functions (see https://mc-stan.org/docs/functions-reference/functions-ode-solver.html for examples), one with defaults and one where you specify all the tolerances.  

> I first want to add a new branch with this feature in Stan/math

You can't do that until you are a Stan developer with permissions.  Which we don't grant to people until they've submitted at least one substantial PR.  Instead, you will need to fork the project, branch from there, then submit a PR from your branch.  When you do that, we'll be able to import your new branch for code review.

**Comment by Franzi2114** [comment] 2022-09-30 09:45
Hi Bob, thanks for your reply!

> then submit a PR from your branch. When you do that, we'll be able to import your new branch for code review.

Is this PR from my fork then the official PR such that my new branch will be merged into the develop branch when it passes code review and all tests OR will it end up in a new branch in Stan/math and another PR is needed for the final merge into the develop branch? I would prefer the latter one, since my plan is that with the pre-publication people who are interested can use the function, test it and give feedback if something should be changed.

**Comment by bob-carpenter** [comment] 2022-09-30 10:44
@Franzi2114:  The former, but PRs can be modified as much as you want before they're merged.  You just push new commits to your branch.  I'd suggest reading some introductions to how PRs work on GitHub, but most of them are so complicated and contain so much extraneous detail that I find them all very confusing.

**Comment by Franzi2114** [comment] 2022-10-07 17:21
The PR ist in progress! (#2822)

The code can be found in my [fork](https://github.com/Franzi2114/math/tree/feature/issue-2682-Add-7-parameter-DDM-PDF). 

An instruction how to integrate this stan version into a local environment can be found [here](https://github.com/Franzi2114/math_HOW-TO-USE).

**Comment by Franzi2114** [comment] 2022-10-12 14:05
Hey @bob-carpenter, 

now the PR for this issue is open (#2822) and all tests run successfully. I have some questions to the next steps: Who starts the workflows and who reviews the code? Shall I ask specific people for this who are firm with this type of function or does the developer team announce reviewers?

Best, Franzi

**Comment by bob-carpenter** [comment] 2022-10-12 22:26
Thanks for submitting.  Anyone with push permission on the project can kick off the continuous integration tests.  So I started them off for you.  I think after that, they will continue to run after updates, but if not, let me know.

Any of our developers are allowed to review anything---we expect people to use their judgement in what they review.  And we only have a single reviewer deciding, so as not to get conflicting reviews, but anyone can comment on a PR.  If you have someone in mind to review, that'd be great.  I'm not really at all familiar with these models, so I shouldn't be the one to to do it.

**Comment by Franzi2114** [comment] 2022-10-19 08:23
Hey @bob-carpenter, 
I already tried to find a person but unfortunately this person was familiar with the function but not with the Stan source code. I checked the Stan developers list but found no other person that had sufficient contact with diffusion models, on the first glance. 

What is the idea of this review process? I ask this because what we implemented strongly follows the WienR package of R, which is implemented in C++. In principle, there is nothing new in the code we provide. It is just adapted to the Stan language. Also the hcubature implementation exists in C++ and in Julia. Therefore, we are pretty sure that the single parts of the function do the things we claim, since we can check 1:1 against the R package. This means that the reviewing person need not necessarily be very familiar with diffusion models. What do you think?

Is it maybe possible to combine knowledge of different people: We have the ones familiar with the function, but not with the Stan language itself, and the ones familiar with the Stan language but not with the function, and the ones maybe with knowledge of both but with no write access.

It seems that in the meantime, no other person did anything with the PR. Should I continue searching for a suitable person? Shall I open a discourse thread on this? Or is there something like an editorial board that asks people for a review? Or do the people still exist that reviewed the wiener_lpdf() function when it had its PR? Is it possible to find out who this was?

Best, Franzi

**Comment by bob-carpenter** [comment] 2022-10-19 09:39
Sorry about that @Franzi2114.  I know how frustrating it is to have written a function and not get it reviewed.  We can definitely have multiple people review. 

Someone familiar with the function should check that the definition makes sense and that there is a sufficient testing plan. @charlesm93 may be able to do that.

Then someone who knows the current state of uur C++ library should be able to review the code.  The most active people on the C++ side these days who are reviewing distribution code are @spinkney and @rok-cesnovar and @andrjohns.   @SteveBronder may also be able to do it.

You can do a search for "wiener" on the closed PRs:  https://github.com/stan-dev/math/pulls?q=is%3Apr+is%3Aclosed

But that's basically broken, not on the GitHub side, but because we do continuous integration regression tests, one of which is the Wiener distribution code, so there are way too many false positives

Scrolling down to ones with "wiener" in the title, it looks like @t4c1 and @bbbales2 were the most recently active, but they graduated and finished their postdocs respectively, and aren't really active on the project any more.

**Comment by charlesm93** [comment] 2022-10-20 12:01
Hi! I'm happy to have a first stab at reviewing the PR. I'm familiar with Stan's process to add features, as well as the C++ (and enough with the OCaml) and I can help with the design of the function and the unit tests. If there is something unorthodox required for the implementation, we can ask @SteveBronder and @WardBrian for help. My familiarity with diffusion processes is elementary but I trust @Franzi2114 and colleagues can get me up to speed. I would do this in two steps: (i) send me a standard reference and (ii) let's have a meeting to walk through the feature. Then I can start reviewing the code.

**Comment by Franzi2114** [comment] 2022-10-20 16:00
> Then I can start reviewing the code.

Hi @charlesm93, thanks for your reply! 
I also saw that @spinkney  started reviewing the contribution. (Thanks for that @spinkney!!) I think he also gets a notification on this discussion here. Since there is a bunch of functions and files we add, it may be helpful to divide the review process and let more people participate? Maybe you get in contact (via the comments in #2822? ) with him and ask how to participate best? (I don't know anything about the review process, so the idea might be stupid).

What do you think @charlesm93?

Here is the standard diffusion model:
Ratcliff, R. (1978). A Theory of Memory Retrieval. Psychological Review ,
85 (2), 59–108.
Here is the extension by Hartmann, and Klauer (2021) with the derivation of the partial derivatives:
Hartmann, R., & Klauer, K. C. (2021). Partial derivatives for the first-passage
time distribution in Wiener diffusion models. Journal of Mathematical
Psychology, 103 , 102550. doi: \url{10.1016/j.jmp.2021.102550} 
And the original hcubature implementation can be found here:
[hcubature](https://github.com/JuliaMath/HCubature.jl)

We can also schedule a meeting to go through the code together if required. Next week?

Thanks a lot! For any questions, just contact me. 
Best, Franzi

**Comment by spinkney** [comment] 2022-10-20 16:32
@charlesm93 I only looked for obvious things and I don't feel confident enough to do a thorough review.

**Comment by spinkney** [comment] 2022-10-20 16:34
> We can also schedule a meeting to go through the code together if required. Next week?

I'm at a conference most of next week but would like to attend this meeting if I can.

**Comment by charlesm93** [comment] 2022-10-21 10:02
@Franzi2114 Thank you for the references.

@spinkney Happy to help out then. I'm in Paris next week, so I also don't mind waiting for the first week of November to meet, if that timeline is fine with @Franzi2114. 

I'll read through https://github.com/stan-dev/math/pull/2822 and get up to speed with the conversation. I suggest @spinkney acts as the main reviewer, and I'll provide support.

**Comment by Franzi2114** [comment] 2022-10-24 11:24
Hey guys (@charlesm93, @spinkney), unfortunately I'm not available next week. Additionally, the feature-freeze for the next Stan-version is on November, 7th. Do you think it is realistic to have the PR done by then? 
I think, having this in mind, it would be better to meet this week. Maybe we find a time slot between your conference talks. I would also suggest to invite my colleague @valentin12 to the meeting and @andrjohns who also had a look on the code, if he is interested.
In the meantime, I will split the PR into 3 PRs and separate the hcubature and the operands_and_partials parts to slim the PR.
What about these dates this week:
-Wednesday 11:30 am (Berlin time)
-Wednesday 6 pm (Berlin time)
-Thursday 2 pm (Berlin time)
-Friday 9:30 am (Berlin time)

**Comment by spinkney** [comment] 2022-10-24 11:28
@Franzi2114 @andrjohns I can meet at the Thursday time. Send the invite to sean.pinkney@gmail.com

**Comment by Franzi2114** [comment] 2022-10-26 10:54
Hey @charlesm93 and @andrjohns,
do you also have time tomorrow at 2pm for a meeting or shall we postpone it?

**Comment by andrjohns** [comment] 2022-10-26 15:16
I have another meeting at that time unfortunately, but I don't think it's essential for me to attend (sounds like Charles and Sean are happy to do the bulk of the reviewing)

**Comment by Franzi2114** [comment] 2022-12-14 16:06
Hi @charlesm93, hi @spinkney, hi @valentin12, how about a meeting this or next week to talk about the PR for the 7-parameter diffusion model? I am currently working on a paper that shows validity of the function. The paper is nearly finished. But the publication more or less depends on the availability of the code in Stan. Therefore it would be nice if this project would go on.

Do you have time on one of the following time slots:
Thursday, 15.12.2022, 2pm Berlin time
Friday, 16.12.2022, 2pm or 3pm Berlin time
Monday, 19.12.2022, 2pm Berlin time
Tuesday, 20.12., 2pm, 3pm or 4pm Berlin time.

Best, Franzi

@andrjohns, you are also invited to participate if you have time.

**Comment by spinkney** [comment] 2022-12-17 15:42
@Franzi2114 sorry no one responded sooner. I am unavailable for the next month. The best folks to take a look at the cpp are @andrjohns or @SteveBronder. 

For the paper, let's not have this be a blocker. You can always fork the repo and build a version of cmdstan with this pr in. @rok-cesnovar can point you to how to do this. First, you'll have to add the distribution to the Stan lang in stanc3 which isn't too hard. @WardBrian can give you a pointer there.

You'll have all the pieces ready to get this in the next release (minus documentation).

**Comment by Franzi2114** [comment] 2022-12-17 19:51
Hey @spinkney, thanks for your reply!

So when I understand you correctly, it should be no problem to hand in the paper and refer to my fork with an instruction how to install this PR manually, so that the reviewers can look at the function although it is not officially included into Stan? That's good news.

I already wrote an instruction how to get started with the function on a linux system [here](https://github.com/Franzi2114/math_HOW-TO-USE). I also explain how to change the Stan_math_signatures.ml in stanc3. At the moment I am struggling on how to get started on a Windows system. I tried it with cross compilation but it still has not been successful. Maybe you have a hint on how proceed there?

**Comment by spinkney** [comment] 2022-12-17 20:58
Even better, you can make a tarball of cmdstan that has your fork of stanmath and stanc3 that they can easily install. They can then download that tar and compile it then use cmdstanr or cmdstanpy as normal.

**Comment by andrjohns** [comment] 2022-12-18 11:13
I'll second @spinkney's apology for the delay! I'll progress the reviews on your PR's over the next week.

For the tarball building, we have a github actions workflow for building `cmdstan` for mac/linux/windows for specified repos and branches of cmdstan/stan/stanc3/math setup. If you can provide the details below, I'll run the workflow to build cmdstan tarballs with your added distribution:

`cmdstan`
- Repo
- Branch

`stanc3`
- Repo
- Branch

`stan`
- Repo
- Branch

`Math`
- Repo
- Branch

**Comment by Franzi2114** [comment] 2022-12-18 13:30
> If you can provide the details below

Up to now I have a fork of stan-dev/math: git@github.com:Franzi2114/math.git
The function is on branch: feature/issue-2682-Add-7-parameter-DDM-PDF

I did not change anything in stan-dev/stan. So I do not have a fork and a branch for this.

Then, I have a clone of stan-dev/stanc3 locally where I changed the following files:
- src/middle/Stan_math_signatures.ml
- test/integration/signatures/stan_math_distributions.t  
- test/integration/signatures/stan_math_signatures.t  
Shall I also fork this stanc3 repo and add the three files on a new branch?

In my llocal cmdstan clone I added the above mentioned math repo and changed the branch, but did not change any other file. So also no fork or branch.

Which information do you need @andrjohns? How many other forks shall I do?

**Comment by andrjohns** [comment] 2022-12-18 13:33
Perfect! Yes if you can create a fork of stanc3 and a branch with your additions (and post the name(s)) here, then I'll start the tarballs building against your modified Math & Stanc3 branches (using the current `develop` branches of CmdStan and Stan)

**Comment by Franzi2114** [comment] 2022-12-18 14:38
Here you are @andrjohns:
My stanc3 Fork is here: git@github.com:Franzi2114/stanc3.git
and the branch has the same name as the other branch: feature/issue-2682-Add-7-parameter-DDM-PDF
I just tested it locally. There it works to compile an example wiener_full.stan file.

So you create these tarballs with which one can install cmdstan with the new function on windows, mac and linux, and all this cross compiling stuff I installed previously is not needed in the stanc3 new fork? (now, there are only 3 files changed)

**Comment by andrjohns** [comment] 2022-12-18 14:55
Great! I've started the workflow running [here](https://github.com/stan-dev/cmdstan/actions/runs/3725347245)

Once it's finished, it will create a cmdstan tarball which uses your fork & branch of the Math library, and has built your fork &  branch of stanc3 for Windows/Mac/Linux. Essentially, the identical format to a release tarball, but with your modifications

**Comment by Franzi2114** [comment] 2022-12-18 17:33
Thanks @andrjohns! This was successful. I just tested it.

I put the cmdstan-ddm-7pm.zip folder into my repo and updated the instruction on how to get started: [https://github.com/Franzi2114/math_HOW-TO-USE](https://github.com/Franzi2114/math_HOW-TO-USE)

**Comment by andrjohns** [comment] 2022-12-19 08:30
Great! You can also add to your README that you can use the tarball with `cmdstanr`/`cmdstanpy` as well, you just need to unzip the folder and set the path to it in `cmdstanr`/`cmdstanpy`

**Comment by Franzi2114** [comment] 2024-03-15 10:18
I merged the PDF branch two days ago. Now, this issue is complete and could be closed.

**Comment by rok-cesnovar** [comment] 2024-03-15 11:33
Thank you!

**Closed by rok-cesnovar** 2024-03-15 11:33 UTC
Labels: feature, distributions
